import { PosterTemplate } from "./types";

export const POSTER_TEMPLATES: PosterTemplate[] = [
  // ===== POLITICAL BANNERS =====
  {
    id: "political-green-1",
    name: "Political Rally - Green",
    nameUrdu: "سیاسی جلسہ",
    category: "Political",
    bgColor: "#006400",
    bgGradient: "linear-gradient(135deg, #004d00 0%, #008000 50%, #006400 100%)",
    elements: [
      { id: "flag-bar", type: "rect", x: 0, y: 0, width: 100, height: 8, bgColor: "#004d00", opacity: 0.9, editable: false },
      { id: "photo", type: "image", x: 35, y: 12, width: 30, height: 30, isPhoto: true, editable: true, bgColor: "rgba(255,255,255,0.2)", borderRadius: 50 },
      { id: "name-urdu", type: "text", x: 10, y: 46, width: 80, height: 10, text: "نام یہاں لکھیں", fontFamily: "Noto Nastaliq Urdu", fontSize: 5, fontWeight: "bold", color: "#FFFFFF", textAlign: "center", direction: "rtl", editable: true },
      { id: "title-urdu", type: "text", x: 10, y: 56, width: 80, height: 8, text: "امیدوار برائے", fontFamily: "Noto Nastaliq Urdu", fontSize: 3.5, color: "#FFD700", textAlign: "center", direction: "rtl", editable: true },
      { id: "slogan", type: "text", x: 5, y: 67, width: 90, height: 12, text: "ترقی کا سفر جاری رہے گا", fontFamily: "Noto Nastaliq Urdu", fontSize: 4, fontWeight: "bold", color: "#FFFFFF", textAlign: "center", direction: "rtl", editable: true },
      { id: "party-bar", type: "rect", x: 0, y: 82, width: 100, height: 18, bgColor: "rgba(0,0,0,0.4)", editable: false },
      { id: "party-name", type: "text", x: 10, y: 85, width: 80, height: 6, text: "پارٹی کا نام", fontFamily: "Noto Nastaliq Urdu", fontSize: 3, color: "#FFD700", textAlign: "center", direction: "rtl", editable: true },
      { id: "contact", type: "text", x: 10, y: 92, width: 80, height: 5, text: "رابطہ: 0300-0000000", fontFamily: "Noto Naskh Arabic", fontSize: 2.5, color: "#FFFFFF", textAlign: "center", direction: "rtl", editable: true },
    ],
  },
  {
    id: "political-red-1",
    name: "Political Campaign - Red",
    nameUrdu: "سیاسی مہم",
    category: "Political",
    bgColor: "#8B0000",
    bgGradient: "linear-gradient(180deg, #8B0000 0%, #CC0000 50%, #8B0000 100%)",
    elements: [
      { id: "top-accent", type: "rect", x: 0, y: 0, width: 100, height: 5, bgColor: "#FFD700", editable: false },
      { id: "photo", type: "image", x: 5, y: 10, width: 35, height: 45, isPhoto: true, editable: true, bgColor: "rgba(255,255,255,0.15)", borderRadius: 5 },
      { id: "name-urdu", type: "text", x: 42, y: 12, width: 55, height: 10, text: "امیدوار کا نام", fontFamily: "Noto Nastaliq Urdu", fontSize: 5, fontWeight: "bold", color: "#FFD700", textAlign: "right", direction: "rtl", editable: true },
      { id: "position", type: "text", x: 42, y: 24, width: 55, height: 8, text: "صدر / چیئرمین", fontFamily: "Noto Nastaliq Urdu", fontSize: 3.5, color: "#FFFFFF", textAlign: "right", direction: "rtl", editable: true },
      { id: "slogan", type: "text", x: 42, y: 35, width: 55, height: 15, text: "عوام کی خدمت ہمارا مشن", fontFamily: "Noto Nastaliq Urdu", fontSize: 3.5, fontWeight: "bold", color: "#FFFFFF", textAlign: "right", direction: "rtl", editable: true },
      { id: "divider", type: "rect", x: 10, y: 58, width: 80, height: 0.5, bgColor: "#FFD700", editable: false },
      { id: "details", type: "text", x: 5, y: 62, width: 90, height: 15, text: "جلسہ عام\n مقام: جناح پارک\nتاریخ: ___________", fontFamily: "Noto Naskh Arabic", fontSize: 3, color: "#FFFFFF", textAlign: "center", direction: "rtl", editable: true, lineHeight: 1.8 },
      { id: "bottom-bar", type: "rect", x: 0, y: 85, width: 100, height: 15, bgColor: "rgba(0,0,0,0.5)", editable: false },
      { id: "contact", type: "text", x: 10, y: 88, width: 80, height: 5, text: "ووٹ ڈالیں - نشان: ___________", fontFamily: "Noto Nastaliq Urdu", fontSize: 3, fontWeight: "bold", color: "#FFD700", textAlign: "center", direction: "rtl", editable: true },
    ],
  },

  // ===== BUSINESS BANNERS =====
  {
    id: "business-blue-1",
    name: "Business Grand Opening",
    nameUrdu: "کاروباری افتتاح",
    category: "Business",
    bgColor: "#1a237e",
    bgGradient: "linear-gradient(135deg, #0d1b4a 0%, #1a237e 50%, #283593 100%)",
    elements: [
      { id: "accent-top", type: "rect", x: 0, y: 0, width: 100, height: 3, bgColor: "#FFD700", editable: false },
      { id: "heading", type: "text", x: 5, y: 8, width: 90, height: 12, text: "گرینڈ اوپننگ", fontFamily: "Noto Nastaliq Urdu", fontSize: 6, fontWeight: "bold", color: "#FFD700", textAlign: "center", direction: "rtl", editable: true },
      { id: "shop-name", type: "text", x: 10, y: 22, width: 80, height: 10, text: "دکان کا نام یہاں لکھیں", fontFamily: "Noto Nastaliq Urdu", fontSize: 4.5, fontWeight: "bold", color: "#FFFFFF", textAlign: "center", direction: "rtl", editable: true },
      { id: "photo", type: "image", x: 25, y: 35, width: 50, height: 25, isPhoto: true, editable: true, bgColor: "rgba(255,255,255,0.1)", borderRadius: 8 },
      { id: "desc", type: "text", x: 10, y: 63, width: 80, height: 10, text: "خصوصی رعایت - ابتدائی گاہکوں کے لیے", fontFamily: "Noto Naskh Arabic", fontSize: 3, color: "#E0E0E0", textAlign: "center", direction: "rtl", editable: true },
      { id: "discount", type: "text", x: 20, y: 74, width: 60, height: 10, text: "50% OFF", fontFamily: "Inter", fontSize: 7, fontWeight: "bold", color: "#FF4444", textAlign: "center", direction: "ltr", editable: true },
      { id: "bottom", type: "rect", x: 0, y: 88, width: 100, height: 12, bgColor: "rgba(0,0,0,0.4)", editable: false },
      { id: "address", type: "text", x: 5, y: 90, width: 90, height: 8, text: "پتہ: ___________ | فون: 0300-0000000", fontFamily: "Noto Naskh Arabic", fontSize: 2.5, color: "#FFFFFF", textAlign: "center", direction: "rtl", editable: true },
    ],
  },
  {
    id: "business-gold-1",
    name: "Business Sale Banner",
    nameUrdu: "سیل بینر",
    category: "Business",
    bgColor: "#1a1a2e",
    bgGradient: "linear-gradient(180deg, #16213e 0%, #1a1a2e 100%)",
    elements: [
      { id: "sale-badge", type: "circle", x: 35, y: 5, width: 30, height: 20, bgColor: "#FF0000", editable: false },
      { id: "sale-text", type: "text", x: 35, y: 8, width: 30, height: 14, text: "SALE", fontFamily: "Inter", fontSize: 5, fontWeight: "bold", color: "#FFFFFF", textAlign: "center", editable: false },
      { id: "title", type: "text", x: 5, y: 28, width: 90, height: 10, text: "بڑی سیل شروع", fontFamily: "Noto Nastaliq Urdu", fontSize: 5.5, fontWeight: "bold", color: "#FFD700", textAlign: "center", direction: "rtl", editable: true },
      { id: "subtitle", type: "text", x: 10, y: 40, width: 80, height: 8, text: "تمام اشیاء پر بھاری رعایت", fontFamily: "Noto Nastaliq Urdu", fontSize: 3.5, color: "#FFFFFF", textAlign: "center", direction: "rtl", editable: true },
      { id: "photo", type: "image", x: 20, y: 50, width: 60, height: 25, isPhoto: true, editable: true, bgColor: "rgba(255,255,255,0.08)", borderRadius: 8 },
      { id: "offer", type: "text", x: 10, y: 78, width: 80, height: 8, text: "70% تک رعایت", fontFamily: "Noto Nastaliq Urdu", fontSize: 4, fontWeight: "bold", color: "#FF4444", textAlign: "center", direction: "rtl", editable: true },
      { id: "contact", type: "text", x: 10, y: 90, width: 80, height: 6, text: "آج ہی تشریف لائیں | 0300-0000000", fontFamily: "Noto Naskh Arabic", fontSize: 2.5, color: "#AAAAAA", textAlign: "center", direction: "rtl", editable: true },
    ],
  },

  // ===== EVENT BANNERS =====
  {
    id: "event-eid-1",
    name: "Eid Mubarak Poster",
    nameUrdu: "عید مبارک پوسٹر",
    category: "Event",
    bgColor: "#1a3a1a",
    bgGradient: "linear-gradient(135deg, #0a2e0a 0%, #1a4d1a 50%, #2d5a2d 100%)",
    elements: [
      { id: "crescent", type: "text", x: 35, y: 3, width: 30, height: 15, text: "☪", fontFamily: "serif", fontSize: 10, color: "#FFD700", textAlign: "center", editable: false },
      { id: "eid-urdu", type: "text", x: 5, y: 20, width: 90, height: 15, text: "عید مبارک", fontFamily: "Noto Nastaliq Urdu", fontSize: 7, fontWeight: "bold", color: "#FFD700", textAlign: "center", direction: "rtl", editable: true },
      { id: "eid-eng", type: "text", x: 20, y: 36, width: 60, height: 6, text: "Eid Mubarak", fontFamily: "Inter", fontSize: 3, color: "#C0C0C0", textAlign: "center", editable: true },
      { id: "photo", type: "image", x: 30, y: 44, width: 40, height: 22, isPhoto: true, editable: true, bgColor: "rgba(255,215,0,0.1)", borderRadius: 50 },
      { id: "message", type: "text", x: 5, y: 69, width: 90, height: 12, text: "آپ کو اور آپ کی فیملی کو\nعید الفطر مبارک ہو", fontFamily: "Noto Nastaliq Urdu", fontSize: 3.5, color: "#FFFFFF", textAlign: "center", direction: "rtl", editable: true, lineHeight: 1.8 },
      { id: "from", type: "text", x: 10, y: 84, width: 80, height: 6, text: "از: آپ کا نام", fontFamily: "Noto Nastaliq Urdu", fontSize: 3, color: "#FFD700", textAlign: "center", direction: "rtl", editable: true },
      { id: "deco-bottom", type: "rect", x: 20, y: 93, width: 60, height: 0.5, bgColor: "#FFD700", opacity: 0.5, editable: false },
    ],
  },
  {
    id: "event-wedding-1",
    name: "Wedding Invitation",
    nameUrdu: "شادی کا کارڈ",
    category: "Event",
    bgColor: "#2c1810",
    bgGradient: "linear-gradient(135deg, #1a0f0a 0%, #3d1f10 50%, #5a2d15 100%)",
    elements: [
      { id: "border-top", type: "rect", x: 3, y: 3, width: 94, height: 0.5, bgColor: "#FFD700", editable: false },
      { id: "border-bottom", type: "rect", x: 3, y: 96, width: 94, height: 0.5, bgColor: "#FFD700", editable: false },
      { id: "heading", type: "text", x: 10, y: 6, width: 80, height: 10, text: "دعوت نامہ", fontFamily: "Noto Nastaliq Urdu", fontSize: 5, fontWeight: "bold", color: "#FFD700", textAlign: "center", direction: "rtl", editable: true },
      { id: "bismillah", type: "text", x: 15, y: 17, width: 70, height: 6, text: "بسم اللہ الرحمٰن الرحیم", fontFamily: "Noto Nastaliq Urdu", fontSize: 3, color: "#FFD700", textAlign: "center", direction: "rtl", editable: true },
      { id: "groom", type: "text", x: 10, y: 28, width: 80, height: 8, text: "دولہا: نام یہاں لکھیں", fontFamily: "Noto Nastaliq Urdu", fontSize: 4, fontWeight: "bold", color: "#FFFFFF", textAlign: "center", direction: "rtl", editable: true },
      { id: "weds", type: "text", x: 30, y: 37, width: 40, height: 6, text: "❤", fontFamily: "serif", fontSize: 4, color: "#FF6B6B", textAlign: "center", editable: false },
      { id: "bride", type: "text", x: 10, y: 44, width: 80, height: 8, text: "دلہن: نام یہاں لکھیں", fontFamily: "Noto Nastaliq Urdu", fontSize: 4, fontWeight: "bold", color: "#FFFFFF", textAlign: "center", direction: "rtl", editable: true },
      { id: "photo", type: "image", x: 25, y: 54, width: 50, height: 20, isPhoto: true, editable: true, bgColor: "rgba(255,215,0,0.08)", borderRadius: 8 },
      { id: "details", type: "text", x: 5, y: 76, width: 90, height: 12, text: "تاریخ: ___________\nمقام: ___________\nوقت: ___________", fontFamily: "Noto Naskh Arabic", fontSize: 2.8, color: "#E0D0C0", textAlign: "center", direction: "rtl", editable: true, lineHeight: 1.8 },
      { id: "footer", type: "text", x: 15, y: 91, width: 70, height: 5, text: "آپ کی تشریف آوری باعثِ عزت ہوگی", fontFamily: "Noto Nastaliq Urdu", fontSize: 2.5, color: "#FFD700", textAlign: "center", direction: "rtl", editable: true },
    ],
  },

  // ===== SOCIAL MEDIA =====
  {
    id: "social-quote-1",
    name: "Social Media Quote",
    nameUrdu: "اقتباس پوسٹ",
    category: "Social Media",
    bgColor: "#0f0f23",
    bgGradient: "linear-gradient(135deg, #0f0f23 0%, #1a1a3e 50%, #2d1b69 100%)",
    elements: [
      { id: "quote-mark", type: "text", x: 10, y: 10, width: 20, height: 15, text: "❝", fontFamily: "serif", fontSize: 10, color: "rgba(255,215,0,0.3)", textAlign: "left", editable: false },
      { id: "quote-text", type: "text", x: 10, y: 25, width: 80, height: 30, text: "یہاں اپنا اقتباس لکھیں\nمشہور شاعری یا حکمت کے الفاظ", fontFamily: "Noto Nastaliq Urdu", fontSize: 4.5, fontWeight: "bold", color: "#FFFFFF", textAlign: "center", direction: "rtl", editable: true, lineHeight: 1.8 },
      { id: "divider", type: "rect", x: 35, y: 58, width: 30, height: 0.4, bgColor: "#FFD700", editable: false },
      { id: "author", type: "text", x: 15, y: 62, width: 70, height: 8, text: "— شاعر / مصنف کا نام", fontFamily: "Noto Nastaliq Urdu", fontSize: 3, color: "#FFD700", textAlign: "center", direction: "rtl", editable: true },
      { id: "photo", type: "image", x: 35, y: 72, width: 30, height: 18, isPhoto: true, editable: true, bgColor: "rgba(255,255,255,0.05)", borderRadius: 50 },
      { id: "handle", type: "text", x: 20, y: 92, width: 60, height: 5, text: "@yourusername", fontFamily: "Inter", fontSize: 2, color: "#888888", textAlign: "center", editable: true },
    ],
  },
  {
    id: "social-promo-1",
    name: "Product Promotion",
    nameUrdu: "پروڈکٹ اشتہار",
    category: "Social Media",
    bgColor: "#1a1a1a",
    bgGradient: "linear-gradient(180deg, #1a1a1a 0%, #2d2d2d 100%)",
    elements: [
      { id: "badge", type: "rect", x: 60, y: 3, width: 35, height: 10, bgColor: "#FF0000", borderRadius: 20, editable: false },
      { id: "badge-text", type: "text", x: 60, y: 4, width: 35, height: 8, text: "NEW", fontFamily: "Inter", fontSize: 3, fontWeight: "bold", color: "#FFFFFF", textAlign: "center", editable: true },
      { id: "product-name", type: "text", x: 5, y: 8, width: 55, height: 12, text: "پروڈکٹ کا نام", fontFamily: "Noto Nastaliq Urdu", fontSize: 5, fontWeight: "bold", color: "#FFFFFF", textAlign: "right", direction: "rtl", editable: true },
      { id: "photo", type: "image", x: 10, y: 22, width: 80, height: 40, isPhoto: true, editable: true, bgColor: "rgba(255,255,255,0.05)", borderRadius: 12 },
      { id: "desc", type: "text", x: 5, y: 65, width: 90, height: 10, text: "بہترین کوالٹی | مناسب قیمت", fontFamily: "Noto Naskh Arabic", fontSize: 3, color: "#CCCCCC", textAlign: "center", direction: "rtl", editable: true },
      { id: "price", type: "text", x: 25, y: 77, width: 50, height: 10, text: "Rs. 999/-", fontFamily: "Inter", fontSize: 5, fontWeight: "bold", color: "#00FF88", textAlign: "center", editable: true },
      { id: "cta", type: "rect", x: 20, y: 89, width: 60, height: 8, bgColor: "#FFD700", borderRadius: 25, editable: false },
      { id: "cta-text", type: "text", x: 20, y: 90, width: 60, height: 6, text: "ابھی آرڈر کریں", fontFamily: "Noto Nastaliq Urdu", fontSize: 2.8, fontWeight: "bold", color: "#000000", textAlign: "center", direction: "rtl", editable: true },
    ],
  },

  // ===== RESTAURANT MENU CARDS =====
  {
    id: "menu-bbq-deals",
    name: "BBQ Deals Menu",
    nameUrdu: "بار بی کیو ڈیلز مینو",
    category: "Menu Card",
    bgColor: "#FFD600",
    bgGradient: "linear-gradient(180deg, #FFD600 0%, #FFA000 100%)",
    elements: [
      { id: "header-bar", type: "rect", x: 0, y: 0, width: 100, height: 12, bgColor: "#D32F2F", editable: false },
      { id: "shop-name", type: "text", x: 5, y: 1, width: 90, height: 10, text: "ریسٹورنٹ کا نام", fontFamily: "Noto Nastaliq Urdu", fontSize: 5, fontWeight: "bold", color: "#FFFFFF", textAlign: "center", direction: "rtl", editable: true },
      { id: "deal1-bg", type: "rect", x: 3, y: 14, width: 30, height: 24, bgColor: "#1A237E", borderRadius: 8, editable: false },
      { id: "deal1-title", type: "text", x: 3, y: 14, width: 30, height: 5, text: "ڈیل 1", fontFamily: "Noto Nastaliq Urdu", fontSize: 2.5, fontWeight: "bold", color: "#FFD700", textAlign: "center", direction: "rtl", editable: true },
      { id: "deal1-items", type: "text", x: 4, y: 19, width: 28, height: 14, text: "1 تکہ بوٹی\n1 چکن کباب\n1 لیٹر بوتل", fontFamily: "Noto Nastaliq Urdu", fontSize: 2, color: "#FFFFFF", textAlign: "right", direction: "rtl", editable: true, lineHeight: 1.6 },
      { id: "deal1-price", type: "text", x: 3, y: 33, width: 30, height: 5, text: "999/-", fontFamily: "Inter", fontSize: 3, fontWeight: "bold", color: "#FF0000", textAlign: "center", editable: true },
      { id: "deal2-bg", type: "rect", x: 35, y: 14, width: 30, height: 24, bgColor: "#1A237E", borderRadius: 8, editable: false },
      { id: "deal2-title", type: "text", x: 35, y: 14, width: 30, height: 5, text: "ڈیل 2", fontFamily: "Noto Nastaliq Urdu", fontSize: 2.5, fontWeight: "bold", color: "#FFD700", textAlign: "center", direction: "rtl", editable: true },
      { id: "deal2-items", type: "text", x: 36, y: 19, width: 28, height: 14, text: "2 تکہ بوٹی\n2 چکن کباب\n1 لیٹر بوتل", fontFamily: "Noto Nastaliq Urdu", fontSize: 2, color: "#FFFFFF", textAlign: "right", direction: "rtl", editable: true, lineHeight: 1.6 },
      { id: "deal2-price", type: "text", x: 35, y: 33, width: 30, height: 5, text: "1499/-", fontFamily: "Inter", fontSize: 3, fontWeight: "bold", color: "#FF0000", textAlign: "center", editable: true },
      { id: "deal3-bg", type: "rect", x: 67, y: 14, width: 30, height: 24, bgColor: "#1A237E", borderRadius: 8, editable: false },
      { id: "deal3-title", type: "text", x: 67, y: 14, width: 30, height: 5, text: "ڈیل 3", fontFamily: "Noto Nastaliq Urdu", fontSize: 2.5, fontWeight: "bold", color: "#FFD700", textAlign: "center", direction: "rtl", editable: true },
      { id: "deal3-items", type: "text", x: 68, y: 19, width: 28, height: 14, text: "3 تکہ بوٹی\n2 ملائی بوٹی\n1.5 لیٹر بوتل", fontFamily: "Noto Nastaliq Urdu", fontSize: 2, color: "#FFFFFF", textAlign: "right", direction: "rtl", editable: true, lineHeight: 1.6 },
      { id: "deal3-price", type: "text", x: 67, y: 33, width: 30, height: 5, text: "1999/-", fontFamily: "Inter", fontSize: 3, fontWeight: "bold", color: "#FF0000", textAlign: "center", editable: true },
      { id: "deal4-bg", type: "rect", x: 3, y: 40, width: 30, height: 24, bgColor: "#1A237E", borderRadius: 8, editable: false },
      { id: "deal4-title", type: "text", x: 3, y: 40, width: 30, height: 5, text: "فیملی ڈیل", fontFamily: "Noto Nastaliq Urdu", fontSize: 2.5, fontWeight: "bold", color: "#FFD700", textAlign: "center", direction: "rtl", editable: true },
      { id: "deal4-items", type: "text", x: 4, y: 45, width: 28, height: 14, text: "4 تکہ بوٹی\n2 کباب\n1 ملائی بوٹی\n1.5 لیٹر بوتل", fontFamily: "Noto Nastaliq Urdu", fontSize: 2, color: "#FFFFFF", textAlign: "right", direction: "rtl", editable: true, lineHeight: 1.6 },
      { id: "deal4-price", type: "text", x: 3, y: 59, width: 30, height: 5, text: "2499/-", fontFamily: "Inter", fontSize: 3, fontWeight: "bold", color: "#FF0000", textAlign: "center", editable: true },
      { id: "deal5-bg", type: "rect", x: 35, y: 40, width: 30, height: 24, bgColor: "#1A237E", borderRadius: 8, editable: false },
      { id: "deal5-title", type: "text", x: 35, y: 40, width: 30, height: 5, text: "سپیشل ڈیل", fontFamily: "Noto Nastaliq Urdu", fontSize: 2.5, fontWeight: "bold", color: "#FFD700", textAlign: "center", direction: "rtl", editable: true },
      { id: "deal5-items", type: "text", x: 36, y: 45, width: 28, height: 14, text: "1 پاؤ چکن\n2 تکہ بوٹی\n2 کباب\n1 لیٹر بوتل", fontFamily: "Noto Nastaliq Urdu", fontSize: 2, color: "#FFFFFF", textAlign: "right", direction: "rtl", editable: true, lineHeight: 1.6 },
      { id: "deal5-price", type: "text", x: 35, y: 59, width: 30, height: 5, text: "2799/-", fontFamily: "Inter", fontSize: 3, fontWeight: "bold", color: "#FF0000", textAlign: "center", editable: true },
      { id: "deal6-bg", type: "rect", x: 67, y: 40, width: 30, height: 24, bgColor: "#1A237E", borderRadius: 8, editable: false },
      { id: "deal6-title", type: "text", x: 67, y: 40, width: 30, height: 5, text: "پارٹی ڈیل", fontFamily: "Noto Nastaliq Urdu", fontSize: 2.5, fontWeight: "bold", color: "#FFD700", textAlign: "center", direction: "rtl", editable: true },
      { id: "deal6-items", type: "text", x: 68, y: 45, width: 28, height: 14, text: "6 تکہ بوٹی\n4 کباب\n2 ملائی بوٹی\n2 لیٹر بوتل", fontFamily: "Noto Nastaliq Urdu", fontSize: 2, color: "#FFFFFF", textAlign: "right", direction: "rtl", editable: true, lineHeight: 1.6 },
      { id: "deal6-price", type: "text", x: 67, y: 59, width: 30, height: 5, text: "3999/-", fontFamily: "Inter", fontSize: 3, fontWeight: "bold", color: "#FF0000", textAlign: "center", editable: true },
      { id: "photo1", type: "image", x: 10, y: 66, width: 25, height: 14, isPhoto: true, editable: true, bgColor: "rgba(255,255,255,0.2)", borderRadius: 8 },
      { id: "photo2", type: "image", x: 38, y: 66, width: 25, height: 14, isPhoto: true, editable: true, bgColor: "rgba(255,255,255,0.2)", borderRadius: 8 },
      { id: "photo3", type: "image", x: 66, y: 66, width: 25, height: 14, isPhoto: true, editable: true, bgColor: "rgba(255,255,255,0.2)", borderRadius: 8 },
      { id: "footer-bar", type: "rect", x: 0, y: 82, width: 100, height: 18, bgColor: "#D32F2F", editable: false },
      { id: "delivery", type: "text", x: 5, y: 83, width: 90, height: 6, text: "فری ہوم ڈیلیوری", fontFamily: "Noto Nastaliq Urdu", fontSize: 4, fontWeight: "bold", color: "#FFFFFF", textAlign: "center", direction: "rtl", editable: true },
      { id: "phone", type: "text", x: 5, y: 90, width: 90, height: 8, text: "0300-0000000 | 0336-0000000", fontFamily: "Inter", fontSize: 3, fontWeight: "bold", color: "#FFD700", textAlign: "center", editable: true },
    ],
  },
  {
    id: "menu-full-price",
    name: "Full Price Menu",
    nameUrdu: "مکمل مینو کارڈ",
    category: "Menu Card",
    bgColor: "#FFF8E1",
    bgGradient: "linear-gradient(180deg, #FFF8E1 0%, #FFE082 100%)",
    elements: [
      { id: "header-bar", type: "rect", x: 0, y: 0, width: 100, height: 14, bgColor: "#C62828", editable: false },
      { id: "shop-name", type: "text", x: 5, y: 1, width: 90, height: 12, text: "ریسٹورنٹ کا نام یہاں لکھیں", fontFamily: "Noto Nastaliq Urdu", fontSize: 5, fontWeight: "bold", color: "#FFFFFF", textAlign: "center", direction: "rtl", editable: true },
      { id: "col1-bg", type: "rect", x: 2, y: 16, width: 30, height: 60, bgColor: "#1A237E", borderRadius: 8, editable: false },
      { id: "col1-title", type: "text", x: 2, y: 16, width: 30, height: 5, text: "پراٹھا", fontFamily: "Noto Nastaliq Urdu", fontSize: 3, fontWeight: "bold", color: "#FFD700", textAlign: "center", direction: "rtl", editable: true },
      { id: "col1-items", type: "text", x: 3, y: 22, width: 28, height: 52, text: "آلو پراٹھا — 110\nانڈہ پراٹھا — 130\nچکن پراٹھا — 220\nبیف قیمہ — 300\nآلو چکن — 200\nچیز پراٹھا — 250", fontFamily: "Noto Nastaliq Urdu", fontSize: 1.8, color: "#FFFFFF", textAlign: "right", direction: "rtl", editable: true, lineHeight: 2.2 },
      { id: "col2-bg", type: "rect", x: 34, y: 16, width: 32, height: 60, bgColor: "#00838F", borderRadius: 8, editable: false },
      { id: "col2-title", type: "text", x: 34, y: 16, width: 32, height: 5, text: "چائے / مشروبات", fontFamily: "Noto Nastaliq Urdu", fontSize: 3, fontWeight: "bold", color: "#FFD700", textAlign: "center", direction: "rtl", editable: true },
      { id: "col2-items", type: "text", x: 35, y: 22, width: 30, height: 52, text: "سادہ چائے — 70\nگڑوالی چائے — 80\nپستہ بادام — 120\nکولڈ ڈرنک — 70\n1 لیٹر کوک — 170\n1.5 لیٹر کوک — 230\nمنرل واٹر — 100", fontFamily: "Noto Nastaliq Urdu", fontSize: 1.8, color: "#FFFFFF", textAlign: "right", direction: "rtl", editable: true, lineHeight: 2.2 },
      { id: "col3-bg", type: "rect", x: 68, y: 16, width: 30, height: 60, bgColor: "#1A237E", borderRadius: 8, editable: false },
      { id: "col3-title", type: "text", x: 68, y: 16, width: 30, height: 5, text: "کھانے", fontFamily: "Noto Nastaliq Urdu", fontSize: 3, fontWeight: "bold", color: "#FFD700", textAlign: "center", direction: "rtl", editable: true },
      { id: "col3-items", type: "text", x: 69, y: 22, width: 28, height: 52, text: "چکن کڑاہی — 1400\nچکن بوٹی — 180\nتکہ بوٹی — 240\nملائی بوٹی — 240\nبیف کباب — 220\nچکن کباب — 170\nلیگ پیس — 300", fontFamily: "Noto Nastaliq Urdu", fontSize: 1.8, color: "#FFFFFF", textAlign: "right", direction: "rtl", editable: true, lineHeight: 2.2 },
      { id: "footer-bar", type: "rect", x: 0, y: 80, width: 100, height: 20, bgColor: "#C62828", editable: false },
      { id: "delivery-text", type: "text", x: 5, y: 81, width: 90, height: 7, text: "فری ہوم ڈیلیوری", fontFamily: "Noto Nastaliq Urdu", fontSize: 4, fontWeight: "bold", color: "#FFD700", textAlign: "center", direction: "rtl", editable: true },
      { id: "phone-nums", type: "text", x: 5, y: 89, width: 90, height: 6, text: "0336-0000000 | 0305-0000000 | 0300-0000000", fontFamily: "Inter", fontSize: 2.5, fontWeight: "bold", color: "#FFFFFF", textAlign: "center", editable: true },
    ],
  },
  {
    id: "menu-simple-card",
    name: "Simple Menu Card",
    nameUrdu: "سادہ مینو کارڈ",
    category: "Menu Card",
    bgColor: "#212121",
    bgGradient: "linear-gradient(180deg, #212121 0%, #333333 100%)",
    elements: [
      { id: "top-accent", type: "rect", x: 0, y: 0, width: 100, height: 3, bgColor: "#FFD700", editable: false },
      { id: "shop-name", type: "text", x: 5, y: 5, width: 90, height: 10, text: "ریسٹورنٹ کا نام", fontFamily: "Noto Nastaliq Urdu", fontSize: 5, fontWeight: "bold", color: "#FFD700", textAlign: "center", direction: "rtl", editable: true },
      { id: "tagline", type: "text", x: 15, y: 15, width: 70, height: 5, text: "ذائقہ جو یاد رہے", fontFamily: "Noto Nastaliq Urdu", fontSize: 2.5, color: "#FFFFFF", textAlign: "center", direction: "rtl", editable: true },
      { id: "divider1", type: "rect", x: 30, y: 21, width: 40, height: 0.3, bgColor: "#FFD700", opacity: 0.5, editable: false },
      { id: "menu-items", type: "text", x: 5, y: 24, width: 90, height: 55, text: "چکن کڑاہی ............ 1400\nچکن بوٹی ............ 180\nتکہ بوٹی ............ 240\nملائی بوٹی ............ 240\nبیف کباب ............ 220\nچکن کباب ............ 170\nلیگ پیس ............ 300\nچیسٹ پیس ............ 380\nرائس فُل ............ 800\nچائے ............ 70\nپراٹھا ............ 110", fontFamily: "Noto Nastaliq Urdu", fontSize: 2.2, color: "#FFFFFF", textAlign: "right", direction: "rtl", editable: true, lineHeight: 2.0 },
      { id: "divider2", type: "rect", x: 30, y: 80, width: 40, height: 0.3, bgColor: "#FFD700", opacity: 0.5, editable: false },
      { id: "photo", type: "image", x: 35, y: 82, width: 30, height: 8, isPhoto: true, editable: true, bgColor: "rgba(255,215,0,0.1)", borderRadius: 8 },
      { id: "contact", type: "text", x: 10, y: 92, width: 80, height: 6, text: "آرڈر کریں: 0300-0000000", fontFamily: "Noto Nastaliq Urdu", fontSize: 2.5, fontWeight: "bold", color: "#FFD700", textAlign: "center", direction: "rtl", editable: true },
    ],
  },
  {
    id: "menu-cafe-modern",
    name: "Modern Cafe Menu",
    nameUrdu: "کیفے مینو",
    category: "Menu Card",
    bgColor: "#1B5E20",
    bgGradient: "linear-gradient(135deg, #1B5E20 0%, #2E7D32 50%, #388E3C 100%)",
    elements: [
      { id: "logo-area", type: "image", x: 35, y: 2, width: 30, height: 12, isPhoto: true, editable: true, bgColor: "rgba(255,255,255,0.15)", borderRadius: 50 },
      { id: "cafe-name", type: "text", x: 5, y: 15, width: 90, height: 8, text: "Cafe Name", fontFamily: "Inter", fontSize: 5, fontWeight: "bold", color: "#FFFFFF", textAlign: "center", editable: true },
      { id: "cafe-urdu", type: "text", x: 15, y: 23, width: 70, height: 5, text: "کیفے کا نام", fontFamily: "Noto Nastaliq Urdu", fontSize: 3, color: "#A5D6A7", textAlign: "center", direction: "rtl", editable: true },
      { id: "sec1-title", type: "text", x: 5, y: 30, width: 45, height: 5, text: "☕ گرم مشروبات", fontFamily: "Noto Nastaliq Urdu", fontSize: 2.5, fontWeight: "bold", color: "#FFD700", textAlign: "right", direction: "rtl", editable: true },
      { id: "sec1-items", type: "text", x: 5, y: 35, width: 45, height: 28, text: "کپوچینو — 350\nلاٹے — 400\nموکا — 450\nامریکانو — 300\nگرین ٹی — 200\nکڑک چائے — 100", fontFamily: "Noto Nastaliq Urdu", fontSize: 1.8, color: "#FFFFFF", textAlign: "right", direction: "rtl", editable: true, lineHeight: 2.2 },
      { id: "sec2-title", type: "text", x: 50, y: 30, width: 45, height: 5, text: "🍔 فوڈ آئٹمز", fontFamily: "Noto Nastaliq Urdu", fontSize: 2.5, fontWeight: "bold", color: "#FFD700", textAlign: "right", direction: "rtl", editable: true },
      { id: "sec2-items", type: "text", x: 50, y: 35, width: 45, height: 28, text: "زنگر برگر — 550\nچکن سینڈوچ — 400\nکلب سینڈوچ — 500\nفرائز — 250\nپاستا — 600\nپیزا — 800", fontFamily: "Noto Nastaliq Urdu", fontSize: 1.8, color: "#FFFFFF", textAlign: "right", direction: "rtl", editable: true, lineHeight: 2.2 },
      { id: "sec3-title", type: "text", x: 5, y: 65, width: 90, height: 5, text: "🧁 ڈیزرٹ", fontFamily: "Noto Nastaliq Urdu", fontSize: 2.5, fontWeight: "bold", color: "#FFD700", textAlign: "center", direction: "rtl", editable: true },
      { id: "sec3-items", type: "text", x: 15, y: 70, width: 70, height: 12, text: "چاکلیٹ کیک — 400 | چیز کیک — 450 | براؤنی — 350", fontFamily: "Noto Nastaliq Urdu", fontSize: 1.8, color: "#FFFFFF", textAlign: "center", direction: "rtl", editable: true, lineHeight: 2.0 },
      { id: "footer-bar", type: "rect", x: 0, y: 84, width: 100, height: 16, bgColor: "rgba(0,0,0,0.4)", editable: false },
      { id: "wifi", type: "text", x: 10, y: 85, width: 80, height: 4, text: "📶 Free WiFi Available", fontFamily: "Inter", fontSize: 2, color: "#A5D6A7", textAlign: "center", editable: true },
      { id: "address", type: "text", x: 5, y: 90, width: 90, height: 8, text: "پتہ یہاں لکھیں | 0300-0000000", fontFamily: "Noto Nastaliq Urdu", fontSize: 2, color: "#FFFFFF", textAlign: "center", direction: "rtl", editable: true },
    ],
  },

  // ===== INVITATION CARDS (carbon-copy of uploaded samples) =====

  // ── Sample 1: Urdu newspaper-style "ریاست علی" landscape card ──
  {
    id: "inv-urdu-newspaper",
    name: "Urdu Newspaper Style Card",
    nameUrdu: "اخباری انداز شادی کارڈ",
    category: "Invitation Card",
    bgColor: "#F5F0E0",
    elements: [
      { id: "top-bar", type: "rect", x: 0, y: 0, width: 100, height: 6, bgColor: "#1A5C2E", editable: false },
      { id: "top-bar-text", type: "text", x: 5, y: 0.5, width: 90, height: 5, text: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ", fontFamily: "Noto Nastaliq Urdu", fontSize: 2.5, color: "#FFFFFF", textAlign: "center", direction: "rtl", editable: true },
      { id: "headline", type: "text", x: 5, y: 8, width: 90, height: 12, text: "ریاست علی", fontFamily: "Noto Nastaliq Urdu", fontSize: 8, fontWeight: "bold", color: "#D4111E", textAlign: "center", direction: "rtl", editable: true },
      { id: "subheading", type: "text", x: 10, y: 20, width: 80, height: 6, text: "برخوردار _________ کی شادی کا اعلان", fontFamily: "Noto Nastaliq Urdu", fontSize: 3, color: "#333333", textAlign: "center", direction: "rtl", editable: true },
      { id: "divider1", type: "rect", x: 5, y: 27, width: 90, height: 0.3, bgColor: "#333333", editable: false },
      { id: "col1-title", type: "text", x: 2, y: 29, width: 30, height: 5, text: "تقریب نکاح", fontFamily: "Noto Nastaliq Urdu", fontSize: 3, fontWeight: "bold", color: "#1A5C2E", textAlign: "center", direction: "rtl", editable: true },
      { id: "col1-body", type: "text", x: 2, y: 35, width: 30, height: 20, text: "بروز جمعہ\n19 اپریل 2026\nنماز: 01:30 بجے\nنکاح: 02:00 بجے", fontFamily: "Noto Nastaliq Urdu", fontSize: 2, color: "#333333", textAlign: "center", direction: "rtl", editable: true, lineHeight: 1.8 },
      { id: "divider-v1", type: "rect", x: 33, y: 29, width: 0.3, height: 30, bgColor: "#999999", editable: false },
      { id: "col2-photo", type: "image", x: 36, y: 29, width: 28, height: 25, isPhoto: true, editable: true, bgColor: "rgba(0,0,0,0.05)", borderRadius: 4 },
      { id: "divider-v2", type: "rect", x: 66, y: 29, width: 0.3, height: 30, bgColor: "#999999", editable: false },
      { id: "col3-title", type: "text", x: 68, y: 29, width: 30, height: 5, text: "تقریب ولیمہ", fontFamily: "Noto Nastaliq Urdu", fontSize: 3, fontWeight: "bold", color: "#1A5C2E", textAlign: "center", direction: "rtl", editable: true },
      { id: "col3-body", type: "text", x: 68, y: 35, width: 30, height: 20, text: "بروز ہفتہ\n20 اپریل 2026\nکھانا: 02:00 بجے\nرخصتی: 04:00 بجے", fontFamily: "Noto Nastaliq Urdu", fontSize: 2, color: "#333333", textAlign: "center", direction: "rtl", editable: true, lineHeight: 1.8 },
      { id: "divider2", type: "rect", x: 5, y: 60, width: 90, height: 0.3, bgColor: "#333333", editable: false },
      { id: "groom-label", type: "text", x: 5, y: 62, width: 40, height: 5, text: "دولہا: _________ ولد _________", fontFamily: "Noto Nastaliq Urdu", fontSize: 2.5, color: "#333333", textAlign: "right", direction: "rtl", editable: true },
      { id: "bride-label", type: "text", x: 55, y: 62, width: 40, height: 5, text: "دلہن: _________ بنت _________", fontFamily: "Noto Nastaliq Urdu", fontSize: 2.5, color: "#333333", textAlign: "right", direction: "rtl", editable: true },
      { id: "venue", type: "text", x: 5, y: 69, width: 90, height: 5, text: "مقام: _________ میرج ہال، _________ روڈ", fontFamily: "Noto Nastaliq Urdu", fontSize: 2.5, fontWeight: "bold", color: "#1A5C2E", textAlign: "center", direction: "rtl", editable: true },
      { id: "divider3", type: "rect", x: 5, y: 75, width: 90, height: 0.3, bgColor: "#333333", editable: false },
      { id: "contacts-heading", type: "text", x: 15, y: 77, width: 70, height: 4, text: "رابطہ نمبرز", fontFamily: "Noto Nastaliq Urdu", fontSize: 2.5, fontWeight: "bold", color: "#D4111E", textAlign: "center", direction: "rtl", editable: true },
      { id: "contacts", type: "text", x: 5, y: 82, width: 90, height: 8, text: "0310-0000000 | 0345-0000000\n0318-0000000 | 0315-0000000", fontFamily: "Inter", fontSize: 2, color: "#333333", textAlign: "center", editable: true, lineHeight: 1.8 },
      { id: "footer-bar", type: "rect", x: 0, y: 92, width: 100, height: 8, bgColor: "#1A5C2E", editable: false },
      { id: "footer-text", type: "text", x: 10, y: 93, width: 80, height: 6, text: "آپ کی تشریف آوری باعثِ عزت ہوگی", fontFamily: "Noto Nastaliq Urdu", fontSize: 2.5, color: "#FFFFFF", textAlign: "center", direction: "rtl", editable: true },
    ],
  },

  // ── Sample 2: Urdu Nikah card with red/gold borders, couple photo ──
  {
    id: "inv-urdu-red-gold-nikah",
    name: "Red & Gold Urdu Nikah Card",
    nameUrdu: "سرخ و سنہری نکاح کارڈ",
    category: "Invitation Card",
    bgColor: "#FAF5EE",
    elements: [
      { id: "outer-border", type: "rect", x: 3, y: 2, width: 94, height: 96, bgColor: "rgba(180,40,40,0.08)", borderRadius: 0, editable: false },
      { id: "red-line-top", type: "rect", x: 6, y: 4, width: 88, height: 0.4, bgColor: "#B22222", editable: false },
      { id: "red-line-bottom", type: "rect", x: 6, y: 95, width: 88, height: 0.4, bgColor: "#B22222", editable: false },
      { id: "red-line-left", type: "rect", x: 6, y: 4, width: 0.3, height: 91.4, bgColor: "#B22222", editable: false },
      { id: "red-line-right", type: "rect", x: 93.7, y: 4, width: 0.3, height: 91.4, bgColor: "#B22222", editable: false },
      { id: "bismillah", type: "text", x: 10, y: 5, width: 80, height: 6, text: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ", fontFamily: "Noto Nastaliq Urdu", fontSize: 3, fontWeight: "bold", color: "#B22222", textAlign: "center", direction: "rtl", editable: true },
      { id: "dawat-heading", type: "text", x: 15, y: 12, width: 70, height: 7, text: "دعوتِ نکاح", fontFamily: "Noto Nastaliq Urdu", fontSize: 5, fontWeight: "bold", color: "#8B6914", textAlign: "center", direction: "rtl", editable: true },
      { id: "invite-text", type: "text", x: 10, y: 20, width: 80, height: 5, text: "راقم الحروف اپنے فرزند کی تقریبِ نکاح پر مدعو کرتے ہیں", fontFamily: "Noto Nastaliq Urdu", fontSize: 2.2, color: "#555555", textAlign: "center", direction: "rtl", editable: true },
      { id: "groom-name", type: "text", x: 10, y: 26, width: 80, height: 7, text: "دولہا کا نام", fontFamily: "Noto Nastaliq Urdu", fontSize: 5, fontWeight: "bold", color: "#B22222", textAlign: "center", direction: "rtl", editable: true },
      { id: "groom-father", type: "text", x: 15, y: 34, width: 70, height: 4, text: "ولد جناب _________ صاحب", fontFamily: "Noto Nastaliq Urdu", fontSize: 2.2, color: "#666666", textAlign: "center", direction: "rtl", editable: true },
      { id: "photo", type: "image", x: 25, y: 39, width: 50, height: 18, isPhoto: true, editable: true, bgColor: "rgba(178,34,34,0.06)", borderRadius: 6 },
      { id: "bride-name", type: "text", x: 10, y: 58, width: 80, height: 7, text: "دلہن کا نام", fontFamily: "Noto Nastaliq Urdu", fontSize: 5, fontWeight: "bold", color: "#B22222", textAlign: "center", direction: "rtl", editable: true },
      { id: "bride-father", type: "text", x: 15, y: 66, width: 70, height: 4, text: "بنت جناب _________ صاحب", fontFamily: "Noto Nastaliq Urdu", fontSize: 2.2, color: "#666666", textAlign: "center", direction: "rtl", editable: true },
      { id: "divider", type: "rect", x: 20, y: 71, width: 60, height: 0.3, bgColor: "#8B6914", editable: false },
      { id: "date", type: "text", x: 10, y: 73, width: 80, height: 5, text: "بروز جمعہ — 19 اپریل 2026", fontFamily: "Noto Nastaliq Urdu", fontSize: 2.8, fontWeight: "bold", color: "#333333", textAlign: "center", direction: "rtl", editable: true },
      { id: "schedule", type: "text", x: 10, y: 79, width: 80, height: 8, text: "نماز: 01:30 | نکاح: 02:00 | کھانا: 02:30 | رخصتی: 04:00", fontFamily: "Noto Nastaliq Urdu", fontSize: 2, color: "#555555", textAlign: "center", direction: "rtl", editable: true },
      { id: "venue", type: "text", x: 10, y: 87, width: 80, height: 4, text: "مقام: _________ میرج ہال", fontFamily: "Noto Nastaliq Urdu", fontSize: 2.5, fontWeight: "bold", color: "#8B6914", textAlign: "center", direction: "rtl", editable: true },
      { id: "contacts", type: "text", x: 15, y: 92, width: 70, height: 3, text: "0310-0000000 | 0345-0000000", fontFamily: "Inter", fontSize: 1.8, color: "#888888", textAlign: "center", editable: true },
    ],
  },

  // ── Sample 3: Dark brown/gold formal English "Nikah" card ──
  {
    id: "inv-english-brown-gold",
    name: "Brown & Gold English Nikah",
    nameUrdu: "براؤن انگریزی نکاح کارڈ",
    category: "Invitation Card",
    bgColor: "#3E2415",
    bgGradient: "linear-gradient(180deg, #4D2E1A 0%, #3E2415 50%, #2A1508 100%)",
    elements: [
      { id: "gold-border-top", type: "rect", x: 4, y: 3, width: 92, height: 0.4, bgColor: "#C9A84C", editable: false },
      { id: "gold-border-bottom", type: "rect", x: 4, y: 96, width: 92, height: 0.4, bgColor: "#C9A84C", editable: false },
      { id: "gold-border-left", type: "rect", x: 4, y: 3, width: 0.3, height: 93.4, bgColor: "#C9A84C", editable: false },
      { id: "gold-border-right", type: "rect", x: 95.7, y: 3, width: 0.3, height: 93.4, bgColor: "#C9A84C", editable: false },
      { id: "corner-deco-tl", type: "rect", x: 4, y: 3, width: 8, height: 5, bgColor: "rgba(201,168,76,0.15)", editable: false },
      { id: "corner-deco-br", type: "rect", x: 88, y: 91, width: 8, height: 5.4, bgColor: "rgba(201,168,76,0.15)", editable: false },
      { id: "invite-label", type: "text", x: 15, y: 6, width: 70, height: 4, text: "We invite you to share in the joy", fontFamily: "Inter", fontSize: 1.8, color: "#C9A84C", textAlign: "center", editable: true },
      { id: "of-all", type: "text", x: 15, y: 10, width: 70, height: 3, text: "of our Daughter's", fontFamily: "Inter", fontSize: 1.5, color: "#E8D5B0", textAlign: "center", editable: true },
      { id: "event-type", type: "text", x: 10, y: 14, width: 80, height: 7, text: "Nikah", fontFamily: "Inter", fontSize: 5.5, fontWeight: "bold", color: "#C9A84C", textAlign: "center", editable: true },
      { id: "of-text2", type: "text", x: 25, y: 22, width: 50, height: 3, text: "of", fontFamily: "Inter", fontSize: 1.8, color: "#BFA67A", textAlign: "center", editable: true },
      { id: "bride-name", type: "text", x: 10, y: 26, width: 80, height: 8, text: "Mehak Malikah", fontFamily: "Inter", fontSize: 5, fontWeight: "bold", color: "#FFFFFF", textAlign: "center", editable: true },
      { id: "d-o", type: "text", x: 15, y: 34, width: 70, height: 3, text: "D/O Daddy Name Sahab", fontFamily: "Inter", fontSize: 1.5, color: "#BFA67A", textAlign: "center", editable: true },
      { id: "with-label", type: "text", x: 35, y: 38, width: 30, height: 4, text: "WITH", fontFamily: "Inter", fontSize: 2.5, color: "#C9A84C", textAlign: "center", editable: false },
      { id: "groom-name", type: "text", x: 10, y: 43, width: 80, height: 8, text: "Groom Full Name", fontFamily: "Inter", fontSize: 5, fontWeight: "bold", color: "#FFFFFF", textAlign: "center", editable: true },
      { id: "s-o", type: "text", x: 15, y: 51, width: 70, height: 3, text: "S/O Father Name Sahab", fontFamily: "Inter", fontSize: 1.5, color: "#BFA67A", textAlign: "center", editable: true },
      { id: "divider", type: "rect", x: 25, y: 56, width: 50, height: 0.3, bgColor: "#C9A84C", editable: false },
      { id: "date", type: "text", x: 10, y: 58, width: 80, height: 6, text: "ON FRIDAY, APRIL 19, 2026", fontFamily: "Inter", fontSize: 2.8, fontWeight: "bold", color: "#C9A84C", textAlign: "center", editable: true },
      { id: "photo", type: "image", x: 25, y: 65, width: 50, height: 14, isPhoto: true, editable: true, bgColor: "rgba(201,168,76,0.08)", borderRadius: 6 },
      { id: "schedule-bg", type: "rect", x: 8, y: 81, width: 84, height: 8, bgColor: "rgba(201,168,76,0.06)", borderRadius: 4, editable: false },
      { id: "schedule", type: "text", x: 10, y: 82, width: 80, height: 6, text: "Barat: 1:00 PM | Namaz: 1:30 PM | Nikkah: 2:15 PM\nLunch: 2:30 PM | Rukhsati: 4:00 PM", fontFamily: "Inter", fontSize: 1.6, color: "#E8D5B0", textAlign: "center", editable: true, lineHeight: 2.0 },
      { id: "venue", type: "text", x: 10, y: 90, width: 80, height: 4, text: "VENUE: _________ MARRIAGE HALL, CITY", fontFamily: "Inter", fontSize: 1.8, fontWeight: "bold", color: "#C9A84C", textAlign: "center", editable: true },
    ],
  },

  // ── Sample 4: Traditional Urdu "دعوت نامہ" with ornate borders ──
  {
    id: "inv-urdu-traditional-dawat",
    name: "Traditional Urdu Dawat Nama",
    nameUrdu: "روایتی اردو دعوت نامہ",
    category: "Invitation Card",
    bgColor: "#F5ECD7",
    elements: [
      { id: "outer-border", type: "rect", x: 2, y: 2, width: 96, height: 96, bgColor: "rgba(139,105,20,0.06)", editable: false },
      { id: "border-top", type: "rect", x: 4, y: 4, width: 92, height: 0.4, bgColor: "#8B6914", editable: false },
      { id: "border-bottom", type: "rect", x: 4, y: 95, width: 92, height: 0.4, bgColor: "#8B6914", editable: false },
      { id: "border-left", type: "rect", x: 4, y: 4, width: 0.3, height: 91.4, bgColor: "#8B6914", editable: false },
      { id: "border-right", type: "rect", x: 95.7, y: 4, width: 0.3, height: 91.4, bgColor: "#8B6914", editable: false },
      { id: "inner-border-top", type: "rect", x: 6, y: 6, width: 88, height: 0.3, bgColor: "#C9A84C", editable: false },
      { id: "inner-border-bottom", type: "rect", x: 6, y: 93, width: 88, height: 0.3, bgColor: "#C9A84C", editable: false },
      { id: "heading-badge", type: "rect", x: 30, y: 7, width: 40, height: 6, bgColor: "rgba(139,105,20,0.1)", borderRadius: 4, editable: false },
      { id: "heading", type: "text", x: 30, y: 7.5, width: 40, height: 5, text: "دعوت نامہ", fontFamily: "Noto Nastaliq Urdu", fontSize: 4, fontWeight: "bold", color: "#8B6914", textAlign: "center", direction: "rtl", editable: true },
      { id: "bismillah", type: "text", x: 10, y: 15, width: 80, height: 7, text: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ", fontFamily: "Noto Nastaliq Urdu", fontSize: 3.5, fontWeight: "bold", color: "#333333", textAlign: "center", direction: "rtl", editable: true },
      { id: "dua", type: "text", x: 8, y: 23, width: 84, height: 6, text: "اَلسَّلاَمُ عَلَيْکُمْ وَرَحْمَۃُ اللّٰهِ وَبَرَکَاتُه", fontFamily: "Noto Nastaliq Urdu", fontSize: 2.5, color: "#555555", textAlign: "center", direction: "rtl", editable: true },
      { id: "host", type: "text", x: 10, y: 30, width: 80, height: 6, text: "جناب محترم _________ صاحب", fontFamily: "Noto Nastaliq Urdu", fontSize: 3, fontWeight: "bold", color: "#333333", textAlign: "center", direction: "rtl", editable: true },
      { id: "invite-line", type: "text", x: 8, y: 37, width: 84, height: 5, text: "اپنے فرزند / فرزندی کی تقریبِ نکاح پر تشریف آوری کی درخواست", fontFamily: "Noto Nastaliq Urdu", fontSize: 2.2, color: "#555555", textAlign: "center", direction: "rtl", editable: true },
      { id: "groom", type: "text", x: 10, y: 43, width: 80, height: 7, text: "دولہا کا نام", fontFamily: "Noto Nastaliq Urdu", fontSize: 5, fontWeight: "bold", color: "#8B6914", textAlign: "center", direction: "rtl", editable: true },
      { id: "weds-urdu", type: "text", x: 30, y: 51, width: 40, height: 4, text: "ولد _________ صاحب", fontFamily: "Noto Nastaliq Urdu", fontSize: 2, color: "#666666", textAlign: "center", direction: "rtl", editable: true },
      { id: "bride", type: "text", x: 10, y: 56, width: 80, height: 7, text: "دلہن کا نام", fontFamily: "Noto Nastaliq Urdu", fontSize: 5, fontWeight: "bold", color: "#8B6914", textAlign: "center", direction: "rtl", editable: true },
      { id: "bride-father", type: "text", x: 30, y: 64, width: 40, height: 4, text: "بنت _________ صاحب", fontFamily: "Noto Nastaliq Urdu", fontSize: 2, color: "#666666", textAlign: "center", direction: "rtl", editable: true },
      { id: "divider", type: "rect", x: 15, y: 69, width: 70, height: 0.3, bgColor: "#8B6914", editable: false },
      { id: "date", type: "text", x: 10, y: 71, width: 80, height: 5, text: "بروز جمعہ — 19 اپریل 2026 بمطابق 19 شوال", fontFamily: "Noto Nastaliq Urdu", fontSize: 2.5, fontWeight: "bold", color: "#333333", textAlign: "center", direction: "rtl", editable: true },
      { id: "schedule", type: "text", x: 10, y: 77, width: 80, height: 8, text: "نماز ......... 01:00 بجے\nنکاح ......... 02:00 بجے\nولیمہ ........ 03:00 بجے\nرخصتی ....... 04:00 بجے", fontFamily: "Noto Nastaliq Urdu", fontSize: 2, color: "#444444", textAlign: "center", direction: "rtl", editable: true, lineHeight: 1.7 },
      { id: "venue", type: "text", x: 10, y: 86, width: 80, height: 4, text: "مقام: _________ میرج ہال، _________ شہر", fontFamily: "Noto Nastaliq Urdu", fontSize: 2.5, fontWeight: "bold", color: "#8B6914", textAlign: "center", direction: "rtl", editable: true },
      { id: "welcome", type: "text", x: 15, y: 91, width: 70, height: 3, text: "آپ کی تشریف آوری باعثِ عزت ہوگی", fontFamily: "Noto Nastaliq Urdu", fontSize: 2, color: "#888888", textAlign: "center", direction: "rtl", editable: true },
    ],
  },

  // ── Sample 5: Dark green multi-panel wedding card ──
  {
    id: "inv-green-multipanel",
    name: "Green Multi-Panel Wedding",
    nameUrdu: "سبز ملٹی پینل شادی کارڈ",
    category: "Invitation Card",
    bgColor: "#0B3D2E",
    bgGradient: "linear-gradient(180deg, #0D4A35 0%, #0B3D2E 50%, #072E22 100%)",
    elements: [
      { id: "gold-ornament-top", type: "rect", x: 30, y: 2, width: 40, height: 3, bgColor: "rgba(201,168,76,0.3)", borderRadius: 20, editable: false },
      { id: "gold-line-top", type: "rect", x: 10, y: 5, width: 80, height: 0.3, bgColor: "#C9A84C", editable: false },
      { id: "wedding-label", type: "text", x: 5, y: 7, width: 90, height: 5, text: "WEDDING INVITATION", fontFamily: "Inter", fontSize: 2.5, fontWeight: "bold", color: "#C9A84C", textAlign: "center", editable: true },
      { id: "couple-names", type: "text", x: 5, y: 13, width: 90, height: 8, text: "Groom Khan\n&\nBride Khan", fontFamily: "Inter", fontSize: 3.5, fontWeight: "bold", color: "#FFFFFF", textAlign: "center", editable: true, lineHeight: 1.4 },
      { id: "divider1", type: "rect", x: 20, y: 23, width: 60, height: 0.3, bgColor: "#C9A84C", editable: false },
      { id: "functions-heading", type: "text", x: 5, y: 25, width: 90, height: 4, text: "FUNCTIONS", fontFamily: "Inter", fontSize: 2.5, fontWeight: "bold", color: "#C9A84C", textAlign: "center", editable: true },
      { id: "mehndi-fn", type: "text", x: 5, y: 30, width: 45, height: 8, text: "MEHNDI CEREMONY\nThursday, April 17\n6:00 PM", fontFamily: "Inter", fontSize: 1.8, color: "#E8D5B0", textAlign: "center", editable: true, lineHeight: 1.6 },
      { id: "nikkah-fn", type: "text", x: 50, y: 30, width: 45, height: 8, text: "NIKKAH CEREMONY\nFriday, April 18\n2:00 PM", fontFamily: "Inter", fontSize: 1.8, color: "#E8D5B0", textAlign: "center", editable: true, lineHeight: 1.6 },
      { id: "walima-fn", type: "text", x: 5, y: 40, width: 45, height: 8, text: "WALIMA\nSaturday, April 19\n1:00 PM", fontFamily: "Inter", fontSize: 1.8, color: "#E8D5B0", textAlign: "center", editable: true, lineHeight: 1.6 },
      { id: "baraat-fn", type: "text", x: 50, y: 40, width: 45, height: 8, text: "BARAAT\nFriday, April 18\n12:00 PM", fontFamily: "Inter", fontSize: 1.8, color: "#E8D5B0", textAlign: "center", editable: true, lineHeight: 1.6 },
      { id: "divider2", type: "rect", x: 20, y: 50, width: 60, height: 0.3, bgColor: "#C9A84C", editable: false },
      { id: "rsvp-heading", type: "text", x: 5, y: 52, width: 90, height: 4, text: "RSVP", fontFamily: "Inter", fontSize: 2.5, fontWeight: "bold", color: "#C9A84C", textAlign: "center", editable: true },
      { id: "rsvp-body", type: "text", x: 10, y: 57, width: 80, height: 6, text: "KINDLY CONFIRM YOUR\nATTENDANCE BY APRIL 10", fontFamily: "Inter", fontSize: 1.8, color: "#E8D5B0", textAlign: "center", editable: true, lineHeight: 1.6 },
      { id: "rsvp-contact", type: "text", x: 10, y: 64, width: 80, height: 4, text: "0310-0000000 | 0345-0000000", fontFamily: "Inter", fontSize: 2, fontWeight: "bold", color: "#FFFFFF", textAlign: "center", editable: true },
      { id: "divider3", type: "rect", x: 20, y: 70, width: 60, height: 0.3, bgColor: "#C9A84C", editable: false },
      { id: "venue-heading", type: "text", x: 5, y: 72, width: 90, height: 4, text: "VENUE", fontFamily: "Inter", fontSize: 2.5, fontWeight: "bold", color: "#C9A84C", textAlign: "center", editable: true },
      { id: "venue-name", type: "text", x: 10, y: 77, width: 80, height: 5, text: "CHEEMA MARRIAGE LAWN", fontFamily: "Inter", fontSize: 2.5, fontWeight: "bold", color: "#FFFFFF", textAlign: "center", editable: true },
      { id: "venue-address", type: "text", x: 10, y: 83, width: 80, height: 6, text: "Sector 22B, Behind MDA Flats\nShah Latif Town, National Highway", fontFamily: "Inter", fontSize: 1.6, color: "#BFA67A", textAlign: "center", editable: true, lineHeight: 1.6 },
      { id: "photo", type: "image", x: 30, y: 90, width: 40, height: 8, isPhoto: true, editable: true, bgColor: "rgba(201,168,76,0.08)", borderRadius: 4 },
      { id: "gold-line-bottom", type: "rect", x: 10, y: 99, width: 80, height: 0.3, bgColor: "#C9A84C", editable: false },
    ],
  },

  // ── Sample 6: Modern blue couple illustration card ──
  {
    id: "inv-modern-blue-couple",
    name: "Modern Blue Wedding Card",
    nameUrdu: "جدید نیلا شادی کارڈ",
    category: "Invitation Card",
    bgColor: "#E8F0FE",
    bgGradient: "linear-gradient(180deg, #D6E6FF 0%, #E8F0FE 40%, #F0F4FF 100%)",
    elements: [
      { id: "floral-accent-top", type: "rect", x: 0, y: 0, width: 100, height: 4, bgColor: "rgba(100,149,237,0.2)", editable: false },
      { id: "programme-label", type: "text", x: 15, y: 5, width: 70, height: 4, text: "PROGRAMME IN-SHA-ALLAH", fontFamily: "Inter", fontSize: 2, fontWeight: "bold", color: "#3B5998", textAlign: "center", editable: true },
      { id: "bismillah", type: "text", x: 10, y: 10, width: 80, height: 6, text: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ", fontFamily: "Noto Nastaliq Urdu", fontSize: 3, color: "#3B5998", textAlign: "center", direction: "rtl", editable: true },
      { id: "parents", type: "text", x: 10, y: 17, width: 80, height: 5, text: "MR. & MRS. FATHER NAME", fontFamily: "Inter", fontSize: 2.5, fontWeight: "bold", color: "#333333", textAlign: "center", editable: true },
      { id: "invite-text", type: "text", x: 10, y: 23, width: 80, height: 5, text: "CORDIALLY INVITE YOU TO THE\nWEDDING CEREMONY OF THEIR SON", fontFamily: "Inter", fontSize: 1.6, color: "#555555", textAlign: "center", editable: true, lineHeight: 1.6 },
      { id: "groom", type: "text", x: 10, y: 30, width: 80, height: 7, text: "Groom Name", fontFamily: "Inter", fontSize: 4.5, fontWeight: "bold", color: "#3B5998", textAlign: "center", editable: true },
      { id: "with", type: "text", x: 35, y: 37, width: 30, height: 3, text: "WITH", fontFamily: "Inter", fontSize: 2, color: "#A7C7E7", textAlign: "center", editable: false },
      { id: "bride", type: "text", x: 10, y: 41, width: 80, height: 7, text: "Bride Name", fontFamily: "Inter", fontSize: 4.5, fontWeight: "bold", color: "#3B5998", textAlign: "center", editable: true },
      { id: "photo", type: "image", x: 15, y: 50, width: 70, height: 22, isPhoto: true, editable: true, bgColor: "rgba(59,89,152,0.06)", borderRadius: 10 },
      { id: "date-day", type: "text", x: 20, y: 74, width: 60, height: 5, text: "MONDAY", fontFamily: "Inter", fontSize: 2.5, fontWeight: "bold", color: "#333333", textAlign: "center", editable: true },
      { id: "date-num", type: "text", x: 30, y: 79, width: 40, height: 7, text: "24", fontFamily: "Inter", fontSize: 6, fontWeight: "bold", color: "#3B5998", textAlign: "center", editable: true },
      { id: "date-rest", type: "text", x: 20, y: 86, width: 60, height: 4, text: "JANUARY AT 1:30 PM", fontFamily: "Inter", fontSize: 2, color: "#555555", textAlign: "center", editable: true },
      { id: "venue", type: "text", x: 10, y: 91, width: 80, height: 4, text: "GATE MARQUEE, GUJRAT ROAD", fontFamily: "Inter", fontSize: 1.8, fontWeight: "bold", color: "#3B5998", textAlign: "center", editable: true },
      { id: "contacts", type: "text", x: 15, y: 96, width: 70, height: 3, text: "0334-0000000 | 0344-0000000", fontFamily: "Inter", fontSize: 1.8, color: "#3B5998", textAlign: "center", editable: true },
    ],
  },

  // ── Sample 7: Classic formal English with Bismillah, schedule table, contacts ──
  {
    id: "inv-classic-english-formal",
    name: "Classic Formal English Card",
    nameUrdu: "کلاسک انگریزی فارمل کارڈ",
    category: "Invitation Card",
    bgColor: "#F5EFE0",
    elements: [
      { id: "corner-tl", type: "rect", x: 2, y: 2, width: 5, height: 4, bgColor: "rgba(60,60,60,0.15)", editable: false },
      { id: "corner-tr", type: "rect", x: 93, y: 2, width: 5, height: 4, bgColor: "rgba(60,60,60,0.15)", editable: false },
      { id: "corner-bl", type: "rect", x: 2, y: 94, width: 5, height: 4, bgColor: "rgba(60,60,60,0.15)", editable: false },
      { id: "corner-br", type: "rect", x: 93, y: 94, width: 5, height: 4, bgColor: "rgba(60,60,60,0.15)", editable: false },
      { id: "bismillah", type: "text", x: 10, y: 4, width: 80, height: 8, text: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ", fontFamily: "Noto Nastaliq Urdu", fontSize: 4.5, fontWeight: "bold", color: "#2C2C2C", textAlign: "center", direction: "rtl", editable: true },
      { id: "parents", type: "text", x: 10, y: 14, width: 80, height: 5, text: "MR. & MRS. NIAZ GUL", fontFamily: "Inter", fontSize: 3, fontWeight: "bold", color: "#2C2C2C", textAlign: "center", editable: true },
      { id: "invite-text", type: "text", x: 8, y: 20, width: 84, height: 4, text: "REQUEST THE PLEASURE OF YOUR COMPANY AT THE", fontFamily: "Inter", fontSize: 1.6, color: "#555555", textAlign: "center", editable: true },
      { id: "ceremony", type: "text", x: 10, y: 25, width: 80, height: 6, text: "\"WEDDING CEREMONY\"", fontFamily: "Inter", fontSize: 3.5, fontWeight: "bold", color: "#2C2C2C", textAlign: "center", editable: true },
      { id: "of-text", type: "text", x: 25, y: 31, width: 50, height: 3, text: "OF THEIR BELOVED DAUGHTER", fontFamily: "Inter", fontSize: 1.3, color: "#777777", textAlign: "center", editable: true },
      { id: "of-word", type: "text", x: 40, y: 34, width: 20, height: 3, text: "OF", fontFamily: "Inter", fontSize: 1.5, color: "#999999", textAlign: "center", editable: true },
      { id: "groom-name", type: "text", x: 10, y: 37, width: 80, height: 7, text: "MUHAMMAD TAHIR", fontFamily: "Inter", fontSize: 4.5, fontWeight: "bold", color: "#333333", textAlign: "center", editable: true },
      { id: "with-label", type: "text", x: 35, y: 44, width: 30, height: 3, text: "WITH", fontFamily: "Inter", fontSize: 2, color: "#888888", textAlign: "center", editable: false },
      { id: "bride-name", type: "text", x: 10, y: 48, width: 80, height: 7, text: "ALI RAZA", fontFamily: "Inter", fontSize: 4.5, fontWeight: "bold", color: "#333333", textAlign: "center", editable: true },
      { id: "son-of", type: "text", x: 15, y: 55, width: 70, height: 3, text: "S/O ZAHID MEHMOOD", fontFamily: "Inter", fontSize: 1.5, color: "#777777", textAlign: "center", editable: true },
      { id: "date-line", type: "text", x: 10, y: 59, width: 80, height: 5, text: "ON SATURDAY 04 FEBRUARY 2023", fontFamily: "Inter", fontSize: 2.8, fontWeight: "bold", color: "#8B6914", textAlign: "center", editable: true },
      { id: "divider1", type: "rect", x: 15, y: 65, width: 70, height: 0.3, bgColor: "#333333", editable: false },
      { id: "schedule-bg", type: "rect", x: 6, y: 67, width: 88, height: 14, bgColor: "rgba(0,0,0,0.03)", borderRadius: 4, editable: false },
      { id: "schedule", type: "text", x: 8, y: 68, width: 84, height: 12, text: "Arrival of Barat: 1:00 PM  |  Namaz: 1:30 PM\nNikkah: 2:15 PM  |  Lunch: 2:30 PM  |  Rukhsati: 4:00 PM", fontFamily: "Inter", fontSize: 1.6, color: "#444444", textAlign: "center", editable: true, lineHeight: 2.2 },
      { id: "divider2", type: "rect", x: 15, y: 82, width: 70, height: 0.3, bgColor: "#333333", editable: false },
      { id: "welcome-heading", type: "text", x: 10, y: 83, width: 80, height: 4, text: "AWAITING TO WELCOME", fontFamily: "Inter", fontSize: 2, fontWeight: "bold", color: "#8B6914", textAlign: "center", editable: true },
      { id: "contacts", type: "text", x: 5, y: 87, width: 90, height: 10, text: "MR & MRS NIAZ GUL        0310-2734204\nMR & MRS MUHAMMAD TAHIR   0345-7797795\nMR HAFIZ SAIF ULLAH       0318-3806489\nMR HAFIZ SAAD ULLAH       0315-2288260\nMR SANA ULLAH             0342-9042005", fontFamily: "Inter", fontSize: 1.3, color: "#333333", textAlign: "center", editable: true, lineHeight: 1.6 },
    ],
  },

  // ── Mehndi Ceremony Card ──
  {
    id: "inv-mehndi-warm",
    name: "Mehndi Ceremony Card",
    nameUrdu: "مہندی تقریب کارڈ",
    category: "Invitation Card",
    bgColor: "#FFF3E0",
    bgGradient: "linear-gradient(180deg, #FFF8E1 0%, #FFE0B2 100%)",
    elements: [
      { id: "top-accent", type: "rect", x: 0, y: 0, width: 100, height: 2, bgColor: "#E65100", editable: false },
      { id: "mehndi-emoji", type: "text", x: 30, y: 4, width: 40, height: 10, text: "🌺", fontFamily: "serif", fontSize: 6, color: "#E65100", textAlign: "center", editable: false },
      { id: "heading-urdu", type: "text", x: 10, y: 15, width: 80, height: 8, text: "تقریبِ مہندی", fontFamily: "Noto Nastaliq Urdu", fontSize: 5, fontWeight: "bold", color: "#E65100", textAlign: "center", direction: "rtl", editable: true },
      { id: "heading-eng", type: "text", x: 20, y: 24, width: 60, height: 4, text: "MEHNDI CEREMONY", fontFamily: "Inter", fontSize: 2.5, fontWeight: "bold", color: "#BF360C", textAlign: "center", editable: true },
      { id: "bride-name", type: "text", x: 10, y: 30, width: 80, height: 8, text: "دلہن کا نام / Bride Name", fontFamily: "Noto Nastaliq Urdu", fontSize: 4, fontWeight: "bold", color: "#333333", textAlign: "center", direction: "rtl", editable: true },
      { id: "photo", type: "image", x: 25, y: 40, width: 50, height: 20, isPhoto: true, editable: true, bgColor: "rgba(230,81,0,0.08)", borderRadius: 50 },
      { id: "date", type: "text", x: 10, y: 63, width: 80, height: 6, text: "بروز جمعرات — 18 اپریل 2026", fontFamily: "Noto Nastaliq Urdu", fontSize: 3, fontWeight: "bold", color: "#E65100", textAlign: "center", direction: "rtl", editable: true },
      { id: "time", type: "text", x: 25, y: 70, width: 50, height: 5, text: "شام 06:00 بجے", fontFamily: "Noto Nastaliq Urdu", fontSize: 2.5, color: "#555555", textAlign: "center", direction: "rtl", editable: true },
      { id: "venue", type: "text", x: 10, y: 77, width: 80, height: 5, text: "مقام: گھر / ہال کا نام", fontFamily: "Noto Nastaliq Urdu", fontSize: 2.5, color: "#BF360C", textAlign: "center", direction: "rtl", editable: true },
      { id: "welcome", type: "text", x: 10, y: 84, width: 80, height: 5, text: "آپ سب خواتین کی تشریف آوری کی درخواست ہے", fontFamily: "Noto Nastaliq Urdu", fontSize: 2, color: "#777777", textAlign: "center", direction: "rtl", editable: true },
      { id: "contact", type: "text", x: 15, y: 91, width: 70, height: 4, text: "رابطہ: 0300-0000000", fontFamily: "Inter", fontSize: 2, color: "#E65100", textAlign: "center", editable: true },
      { id: "bottom-accent", type: "rect", x: 0, y: 97, width: 100, height: 3, bgColor: "#E65100", editable: false },
    ],
  },

  // ── Baraat Card (Dark/Gold) ──
  {
    id: "inv-baraat-dark-gold",
    name: "Baraat Card — Dark Gold",
    nameUrdu: "بارات کارڈ",
    category: "Invitation Card",
    bgColor: "#1A0A0A",
    bgGradient: "linear-gradient(180deg, #2C1010 0%, #1A0A0A 100%)",
    elements: [
      { id: "gold-top", type: "rect", x: 0, y: 0, width: 100, height: 2, bgColor: "#FFD700", editable: false },
      { id: "bismillah", type: "text", x: 10, y: 4, width: 80, height: 7, text: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ", fontFamily: "Noto Nastaliq Urdu", fontSize: 3.5, fontWeight: "bold", color: "#FFD700", textAlign: "center", direction: "rtl", editable: true },
      { id: "heading", type: "text", x: 10, y: 13, width: 80, height: 8, text: "دعوتِ بارات", fontFamily: "Noto Nastaliq Urdu", fontSize: 5, fontWeight: "bold", color: "#FF4444", textAlign: "center", direction: "rtl", editable: true },
      { id: "host", type: "text", x: 10, y: 22, width: 80, height: 5, text: "جناب _________ صاحب", fontFamily: "Noto Nastaliq Urdu", fontSize: 3, color: "#E8D5B0", textAlign: "center", direction: "rtl", editable: true },
      { id: "invite-line", type: "text", x: 10, y: 28, width: 80, height: 5, text: "اپنے فرزند کی بارات پر مدعو کرتے ہیں", fontFamily: "Noto Nastaliq Urdu", fontSize: 2.5, color: "#CCCCCC", textAlign: "center", direction: "rtl", editable: true },
      { id: "groom", type: "text", x: 10, y: 34, width: 80, height: 8, text: "دولہا کا نام", fontFamily: "Noto Nastaliq Urdu", fontSize: 5.5, fontWeight: "bold", color: "#FFFFFF", textAlign: "center", direction: "rtl", editable: true },
      { id: "photo", type: "image", x: 30, y: 44, width: 40, height: 16, isPhoto: true, editable: true, bgColor: "rgba(255,215,0,0.08)", borderRadius: 50 },
      { id: "date", type: "text", x: 10, y: 62, width: 80, height: 6, text: "بروز جمعہ — 19 اپریل 2026", fontFamily: "Noto Nastaliq Urdu", fontSize: 3, fontWeight: "bold", color: "#FFD700", textAlign: "center", direction: "rtl", editable: true },
      { id: "schedule-bg", type: "rect", x: 8, y: 70, width: 84, height: 12, bgColor: "rgba(255,215,0,0.06)", borderRadius: 6, editable: false },
      { id: "schedule", type: "text", x: 10, y: 71, width: 80, height: 10, text: "روانگی بارات ... 12:00 بجے\nنماز .............. 01:00 بجے\nنکاح .............. 01:30 بجے\nکھانا .............. 02:00 بجے", fontFamily: "Noto Nastaliq Urdu", fontSize: 2, color: "#E8D5B0", textAlign: "center", direction: "rtl", editable: true, lineHeight: 1.8 },
      { id: "venue", type: "text", x: 10, y: 84, width: 80, height: 5, text: "مقام روانگی: _________ مسجد / گھر", fontFamily: "Noto Nastaliq Urdu", fontSize: 2.5, color: "#FFD700", textAlign: "center", direction: "rtl", editable: true },
      { id: "contacts", type: "text", x: 10, y: 91, width: 80, height: 4, text: "0310-0000000 | 0345-0000000", fontFamily: "Inter", fontSize: 2, color: "#CCCCCC", textAlign: "center", editable: true },
      { id: "gold-bottom", type: "rect", x: 0, y: 97, width: 100, height: 3, bgColor: "#FFD700", editable: false },
    ],
  },

  // ── Walima Card (Blue) ──
  {
    id: "inv-walima-blue",
    name: "Walima Card — Blue",
    nameUrdu: "ولیمہ کارڈ",
    category: "Invitation Card",
    bgColor: "#E8F0FE",
    elements: [
      { id: "top-floral", type: "rect", x: 0, y: 0, width: 100, height: 3, bgColor: "#A7C7E7", editable: false },
      { id: "bismillah", type: "text", x: 15, y: 5, width: 70, height: 6, text: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ", fontFamily: "Noto Nastaliq Urdu", fontSize: 3, color: "#3B5998", textAlign: "center", direction: "rtl", editable: true },
      { id: "parents", type: "text", x: 10, y: 12, width: 80, height: 5, text: "MR. & MRS. FATHER NAME", fontFamily: "Inter", fontSize: 2.5, fontWeight: "bold", color: "#333333", textAlign: "center", editable: true },
      { id: "invite-text", type: "text", x: 10, y: 18, width: 80, height: 5, text: "CORDIALLY INVITE YOU AT THE\nWALIMA CEREMONY OF THEIR BELOVED SON", fontFamily: "Inter", fontSize: 1.8, color: "#555555", textAlign: "center", editable: true, lineHeight: 1.6 },
      { id: "groom", type: "text", x: 10, y: 26, width: 80, height: 8, text: "Groom Name", fontFamily: "Inter", fontSize: 5, fontWeight: "bold", color: "#3B5998", textAlign: "center", editable: true },
      { id: "with", type: "text", x: 35, y: 34, width: 30, height: 3, text: "WITH", fontFamily: "Inter", fontSize: 2, color: "#A7C7E7", textAlign: "center", editable: false },
      { id: "bride", type: "text", x: 10, y: 38, width: 80, height: 8, text: "Bride Name", fontFamily: "Inter", fontSize: 5, fontWeight: "bold", color: "#3B5998", textAlign: "center", editable: true },
      { id: "photo", type: "image", x: 20, y: 48, width: 60, height: 20, isPhoto: true, editable: true, bgColor: "rgba(59,89,152,0.08)", borderRadius: 8 },
      { id: "date-big", type: "text", x: 20, y: 70, width: 60, height: 10, text: "Monday\n24\nJAN AT 1:30 PM", fontFamily: "Inter", fontSize: 3, fontWeight: "bold", color: "#333333", textAlign: "center", editable: true, lineHeight: 1.4 },
      { id: "venue", type: "text", x: 10, y: 82, width: 80, height: 5, text: "VENUE: GRACE MARQUEE, MAIN ROAD, CITY", fontFamily: "Inter", fontSize: 1.8, color: "#555555", textAlign: "center", editable: true },
      { id: "contacts", type: "text", x: 10, y: 89, width: 80, height: 5, text: "0334-0000000 | 0344-0000000", fontFamily: "Inter", fontSize: 1.8, color: "#3B5998", textAlign: "center", editable: true },
      { id: "bottom-floral", type: "rect", x: 0, y: 97, width: 100, height: 3, bgColor: "#A7C7E7", editable: false },
    ],
  },

  // ── Birthday Invitation ──
  {
    id: "inv-birthday-bright",
    name: "Birthday Invitation",
    nameUrdu: "سالگرہ دعوت نامہ",
    category: "Invitation Card",
    bgColor: "#FF6B8A",
    bgGradient: "linear-gradient(135deg, #FF6B8A 0%, #FF8E53 50%, #FFA726 100%)",
    elements: [
      { id: "balloons", type: "text", x: 25, y: 3, width: 50, height: 10, text: "🎈🎂🎈", fontFamily: "serif", fontSize: 6, color: "#FFFFFF", textAlign: "center", editable: false },
      { id: "heading", type: "text", x: 5, y: 14, width: 90, height: 10, text: "HAPPY BIRTHDAY!", fontFamily: "Inter", fontSize: 5, fontWeight: "bold", color: "#FFFFFF", textAlign: "center", editable: true },
      { id: "heading-urdu", type: "text", x: 15, y: 25, width: 70, height: 6, text: "سالگرہ مبارک", fontFamily: "Noto Nastaliq Urdu", fontSize: 4, fontWeight: "bold", color: "#FFFFFF", textAlign: "center", direction: "rtl", editable: true },
      { id: "name", type: "text", x: 10, y: 33, width: 80, height: 10, text: "نام یہاں لکھیں", fontFamily: "Noto Nastaliq Urdu", fontSize: 5, fontWeight: "bold", color: "#FFFFFF", textAlign: "center", direction: "rtl", editable: true },
      { id: "photo", type: "image", x: 25, y: 45, width: 50, height: 20, isPhoto: true, editable: true, bgColor: "rgba(255,255,255,0.2)", borderRadius: 50 },
      { id: "invite-line", type: "text", x: 10, y: 68, width: 80, height: 5, text: "آپ سب کو سالگرہ کی تقریب پر مدعو کیا جاتا ہے", fontFamily: "Noto Nastaliq Urdu", fontSize: 2.5, color: "#FFFFFF", textAlign: "center", direction: "rtl", editable: true },
      { id: "date", type: "text", x: 15, y: 75, width: 70, height: 5, text: "بروز ہفتہ — 19 اپریل 2026", fontFamily: "Noto Nastaliq Urdu", fontSize: 2.5, fontWeight: "bold", color: "#FFFFFF", textAlign: "center", direction: "rtl", editable: true },
      { id: "time", type: "text", x: 25, y: 81, width: 50, height: 4, text: "شام 05:00 بجے", fontFamily: "Noto Nastaliq Urdu", fontSize: 2.5, color: "#FFFFFF", textAlign: "center", direction: "rtl", editable: true },
      { id: "venue", type: "text", x: 10, y: 87, width: 80, height: 4, text: "مقام: _________ ", fontFamily: "Noto Nastaliq Urdu", fontSize: 2.5, color: "#FFFFFF", textAlign: "center", direction: "rtl", editable: true },
      { id: "contact", type: "text", x: 20, y: 93, width: 60, height: 4, text: "RSVP: 0300-0000000", fontFamily: "Inter", fontSize: 2, fontWeight: "bold", color: "#FFFFFF", textAlign: "center", editable: true },
    ],
  },

  // ── Business Opening Invite ──
  {
    id: "inv-business-opening",
    name: "Business Opening Invite",
    nameUrdu: "افتتاحی دعوت نامہ",
    category: "Invitation Card",
    bgColor: "#0D1B2A",
    bgGradient: "linear-gradient(180deg, #1B2838 0%, #0D1B2A 100%)",
    elements: [
      { id: "accent-top", type: "rect", x: 0, y: 0, width: 100, height: 2, bgColor: "#FFD700", editable: false },
      { id: "invite-label", type: "text", x: 20, y: 5, width: 60, height: 5, text: "YOU ARE INVITED", fontFamily: "Inter", fontSize: 2.5, fontWeight: "bold", color: "#FFD700", textAlign: "center", editable: true },
      { id: "heading", type: "text", x: 5, y: 13, width: 90, height: 10, text: "GRAND OPENING", fontFamily: "Inter", fontSize: 5, fontWeight: "bold", color: "#FFFFFF", textAlign: "center", editable: true },
      { id: "business-name", type: "text", x: 10, y: 25, width: 80, height: 8, text: "Business / Shop Name", fontFamily: "Inter", fontSize: 4.5, fontWeight: "bold", color: "#FFD700", textAlign: "center", editable: true },
      { id: "photo", type: "image", x: 20, y: 35, width: 60, height: 22, isPhoto: true, editable: true, bgColor: "rgba(255,215,0,0.08)", borderRadius: 8 },
      { id: "date", type: "text", x: 10, y: 60, width: 80, height: 6, text: "Sunday, April 19, 2026", fontFamily: "Inter", fontSize: 3, fontWeight: "bold", color: "#FFFFFF", textAlign: "center", editable: true },
      { id: "time", type: "text", x: 25, y: 67, width: 50, height: 5, text: "5:00 PM Onwards", fontFamily: "Inter", fontSize: 2.5, color: "#FFD700", textAlign: "center", editable: true },
      { id: "chief-guest", type: "text", x: 10, y: 74, width: 80, height: 6, text: "Chief Guest: __________", fontFamily: "Inter", fontSize: 2.5, color: "#E0E0E0", textAlign: "center", editable: true },
      { id: "venue", type: "text", x: 10, y: 82, width: 80, height: 5, text: "Location: _________ Road, City", fontFamily: "Inter", fontSize: 2, color: "#FFFFFF", textAlign: "center", editable: true },
      { id: "contact", type: "text", x: 15, y: 89, width: 70, height: 4, text: "Contact: 0300-0000000", fontFamily: "Inter", fontSize: 2, color: "#FFD700", textAlign: "center", editable: true },
      { id: "accent-bottom", type: "rect", x: 0, y: 95, width: 100, height: 5, bgColor: "#FFD700", editable: false },
    ],
  },

  // ── Party Invitation ──
  {
    id: "inv-party-purple",
    name: "Party Invitation",
    nameUrdu: "پارٹی دعوت نامہ",
    category: "Invitation Card",
    bgColor: "#1A0A2E",
    bgGradient: "linear-gradient(135deg, #1A0A2E 0%, #2D1B69 50%, #4A1A8A 100%)",
    elements: [
      { id: "sparkle", type: "text", x: 30, y: 3, width: 40, height: 10, text: "🎉", fontFamily: "serif", fontSize: 6, color: "#FFD700", textAlign: "center", editable: false },
      { id: "heading", type: "text", x: 5, y: 14, width: 90, height: 10, text: "YOU'RE INVITED!", fontFamily: "Inter", fontSize: 5, fontWeight: "bold", color: "#FFD700", textAlign: "center", editable: true },
      { id: "event-name", type: "text", x: 10, y: 26, width: 80, height: 8, text: "Event Name", fontFamily: "Inter", fontSize: 5, fontWeight: "bold", color: "#FFFFFF", textAlign: "center", editable: true },
      { id: "desc", type: "text", x: 15, y: 36, width: 70, height: 6, text: "Birthday / Party / Gathering", fontFamily: "Inter", fontSize: 3, color: "#E0B0FF", textAlign: "center", editable: true },
      { id: "photo", type: "image", x: 25, y: 44, width: 50, height: 18, isPhoto: true, editable: true, bgColor: "rgba(255,215,0,0.08)", borderRadius: 50 },
      { id: "date", type: "text", x: 15, y: 65, width: 70, height: 6, text: "Saturday, April 19, 2026", fontFamily: "Inter", fontSize: 3, fontWeight: "bold", color: "#FFD700", textAlign: "center", editable: true },
      { id: "time", type: "text", x: 25, y: 72, width: 50, height: 5, text: "7:00 PM", fontFamily: "Inter", fontSize: 2.5, color: "#FFFFFF", textAlign: "center", editable: true },
      { id: "venue", type: "text", x: 10, y: 79, width: 80, height: 5, text: "Venue: _________ Hall", fontFamily: "Inter", fontSize: 2.5, color: "#E0B0FF", textAlign: "center", editable: true },
      { id: "dress-code", type: "text", x: 20, y: 86, width: 60, height: 4, text: "Dress Code: Formal", fontFamily: "Inter", fontSize: 2, color: "#FFD700", textAlign: "center", editable: true },
      { id: "rsvp", type: "text", x: 20, y: 92, width: 60, height: 4, text: "RSVP: 0300-0000000", fontFamily: "Inter", fontSize: 2, fontWeight: "bold", color: "#FFFFFF", textAlign: "center", editable: true },
    ],
  },

  // ===== BUSINESS CARDS =====
  {
    id: "bcard-modern-1",
    name: "Modern Minimal Card",
    category: "Business Card",
    bgColor: "#FFFFFF",
    bgGradient: "linear-gradient(135deg, #FFFFFF 0%, #F0F0F0 100%)",
    elements: [
      { id: "accent-bar", type: "rect", x: 0, y: 0, width: 100, height: 6, bgColor: "#1a237e", editable: false },
      { id: "name", type: "text", x: 6, y: 18, width: 88, height: 16, text: "John Doe", fontFamily: "Inter", fontSize: 7, fontWeight: "bold", color: "#1a237e", textAlign: "left", editable: true },
      { id: "title", type: "text", x: 6, y: 36, width: 88, height: 10, text: "Senior Designer", fontFamily: "Inter", fontSize: 4, color: "#555555", textAlign: "left", editable: true },
      { id: "divider", type: "rect", x: 6, y: 52, width: 25, height: 1, bgColor: "#1a237e", editable: false },
      { id: "phone", type: "text", x: 6, y: 60, width: 88, height: 8, text: "📞 +92 300 1234567", fontFamily: "Inter", fontSize: 3.5, color: "#333333", textAlign: "left", editable: true },
      { id: "email", type: "text", x: 6, y: 70, width: 88, height: 8, text: "✉ john@company.com", fontFamily: "Inter", fontSize: 3.5, color: "#333333", textAlign: "left", editable: true },
      { id: "website", type: "text", x: 6, y: 80, width: 88, height: 8, text: "🌐 www.company.com", fontFamily: "Inter", fontSize: 3.5, color: "#333333", textAlign: "left", editable: true },
      { id: "logo", type: "image", x: 72, y: 14, width: 22, height: 22, isPhoto: true, editable: true, bgColor: "rgba(26,35,126,0.08)", borderRadius: 8 },
    ],
  },
  {
    id: "bcard-dark-1",
    name: "Dark Professional Card",
    category: "Business Card",
    bgColor: "#1a1a2e",
    bgGradient: "linear-gradient(135deg, #16213e 0%, #1a1a2e 50%, #0f3460 100%)",
    elements: [
      { id: "accent", type: "rect", x: 0, y: 88, width: 100, height: 12, bgColor: "#e94560", editable: false },
      { id: "logo", type: "image", x: 6, y: 10, width: 20, height: 20, isPhoto: true, editable: true, bgColor: "rgba(255,255,255,0.08)", borderRadius: 50 },
      { id: "name", type: "text", x: 6, y: 38, width: 88, height: 14, text: "AHMED KHAN", fontFamily: "Inter", fontSize: 6.5, fontWeight: "bold", color: "#FFFFFF", textAlign: "left", editable: true },
      { id: "title", type: "text", x: 6, y: 54, width: 88, height: 8, text: "CEO & Founder", fontFamily: "Inter", fontSize: 3.5, color: "#e94560", textAlign: "left", editable: true },
      { id: "phone", type: "text", x: 6, y: 68, width: 45, height: 7, text: "+92 300 1234567", fontFamily: "Inter", fontSize: 3, color: "#CCCCCC", textAlign: "left", editable: true },
      { id: "email", type: "text", x: 50, y: 68, width: 45, height: 7, text: "ahmed@business.pk", fontFamily: "Inter", fontSize: 3, color: "#CCCCCC", textAlign: "left", editable: true },
      { id: "address", type: "text", x: 6, y: 78, width: 88, height: 7, text: "Office 12, Blue Area, Islamabad", fontFamily: "Inter", fontSize: 2.8, color: "#999999", textAlign: "left", editable: true },
    ],
  },
  {
    id: "bcard-urdu-1",
    name: "Urdu Business Card",
    nameUrdu: "اردو بزنس کارڈ",
    category: "Business Card",
    bgColor: "#FFFFFF",
    bgGradient: "linear-gradient(180deg, #FFFFFF 0%, #f5f0e8 100%)",
    elements: [
      { id: "border", type: "rect", x: 2, y: 2, width: 96, height: 96, bgColor: "transparent", borderRadius: 4, editable: false },
      { id: "accent", type: "rect", x: 0, y: 0, width: 3, height: 100, bgColor: "#2e7d32", editable: false },
      { id: "name", type: "text", x: 8, y: 12, width: 84, height: 16, text: "محمد احمد", fontFamily: "Noto Nastaliq Urdu", fontSize: 7, fontWeight: "bold", color: "#2e7d32", textAlign: "right", direction: "rtl", editable: true },
      { id: "title", type: "text", x: 8, y: 32, width: 84, height: 10, text: "مالک / ڈائریکٹر", fontFamily: "Noto Nastaliq Urdu", fontSize: 4, color: "#555555", textAlign: "right", direction: "rtl", editable: true },
      { id: "divider", type: "rect", x: 50, y: 48, width: 42, height: 1, bgColor: "#2e7d32", editable: false },
      { id: "phone", type: "text", x: 8, y: 56, width: 84, height: 8, text: "فون: 0300-1234567", fontFamily: "Noto Naskh Arabic", fontSize: 3.5, color: "#333333", textAlign: "right", direction: "rtl", editable: true },
      { id: "address", type: "text", x: 8, y: 68, width: 84, height: 12, text: "پتہ: آفس نمبر 5، بلیو ایریا، اسلام آباد", fontFamily: "Noto Naskh Arabic", fontSize: 3, color: "#555555", textAlign: "right", direction: "rtl", editable: true },
      { id: "logo", type: "image", x: 8, y: 12, width: 18, height: 18, isPhoto: true, editable: true, bgColor: "rgba(46,125,50,0.08)", borderRadius: 8 },
    ],
  },
  {
    id: "bcard-gradient-1",
    name: "Gradient Premium Card",
    category: "Business Card",
    bgColor: "#6366f1",
    bgGradient: "linear-gradient(135deg, #6366f1 0%, #8b5cf6 50%, #a855f7 100%)",
    elements: [
      { id: "name", type: "text", x: 8, y: 16, width: 60, height: 16, text: "Sara Ali", fontFamily: "Inter", fontSize: 7, fontWeight: "bold", color: "#FFFFFF", textAlign: "left", editable: true },
      { id: "title", type: "text", x: 8, y: 34, width: 60, height: 8, text: "Marketing Director", fontFamily: "Inter", fontSize: 3.5, color: "rgba(255,255,255,0.8)", textAlign: "left", editable: true },
      { id: "logo", type: "image", x: 72, y: 10, width: 22, height: 22, isPhoto: true, editable: true, bgColor: "rgba(255,255,255,0.15)", borderRadius: 50 },
      { id: "divider", type: "rect", x: 8, y: 50, width: 84, height: 0.5, bgColor: "rgba(255,255,255,0.3)", editable: false },
      { id: "phone", type: "text", x: 8, y: 58, width: 84, height: 8, text: "📞 +92 321 9876543", fontFamily: "Inter", fontSize: 3.2, color: "#FFFFFF", textAlign: "left", editable: true },
      { id: "email", type: "text", x: 8, y: 68, width: 84, height: 8, text: "✉ sara@agency.com", fontFamily: "Inter", fontSize: 3.2, color: "#FFFFFF", textAlign: "left", editable: true },
      { id: "web", type: "text", x: 8, y: 78, width: 84, height: 8, text: "🌐 www.agency.com", fontFamily: "Inter", fontSize: 3.2, color: "rgba(255,255,255,0.8)", textAlign: "left", editable: true },
    ],
  },

  // ===== BUSINESS PADS / LETTERHEADS =====
  {
    id: "bpad-corporate-1",
    name: "Corporate Letterhead",
    category: "Business Pad",
    bgColor: "#FFFFFF",
    elements: [
      { id: "top-bar", type: "rect", x: 0, y: 0, width: 100, height: 3, bgColor: "#1a237e", editable: false },
      { id: "logo", type: "image", x: 5, y: 4, width: 12, height: 6, isPhoto: true, editable: true, bgColor: "rgba(26,35,126,0.06)", borderRadius: 4 },
      { id: "company", type: "text", x: 20, y: 4, width: 60, height: 4, text: "COMPANY NAME", fontFamily: "Inter", fontSize: 2.5, fontWeight: "bold", color: "#1a237e", textAlign: "left", editable: true },
      { id: "tagline", type: "text", x: 20, y: 7.5, width: 60, height: 2.5, text: "Your Tagline Here", fontFamily: "Inter", fontSize: 1.5, color: "#666666", textAlign: "left", editable: true },
      { id: "divider-top", type: "rect", x: 5, y: 12, width: 90, height: 0.15, bgColor: "#1a237e", editable: false },
      { id: "body", type: "text", x: 8, y: 16, width: 84, height: 65, text: "Dear Sir/Madam,\n\nType your letter content here...\n\n\n\n\n\nSincerely,\nYour Name\nDesignation", fontFamily: "Inter", fontSize: 1.8, color: "#333333", textAlign: "left", editable: true, lineHeight: 2 },
      { id: "divider-bottom", type: "rect", x: 5, y: 90, width: 90, height: 0.15, bgColor: "#1a237e", editable: false },
      { id: "footer-address", type: "text", x: 5, y: 92, width: 90, height: 3, text: "Office No. 12, Blue Area, Islamabad | +92 300 1234567 | info@company.com", fontFamily: "Inter", fontSize: 1.2, color: "#888888", textAlign: "center", editable: true },
      { id: "footer-web", type: "text", x: 5, y: 95.5, width: 90, height: 2.5, text: "www.company.com", fontFamily: "Inter", fontSize: 1.2, color: "#1a237e", textAlign: "center", editable: true },
    ],
  },
  {
    id: "bpad-urdu-1",
    name: "Urdu Letterpad",
    nameUrdu: "اردو لیٹر پیڈ",
    category: "Business Pad",
    bgColor: "#FFFFFF",
    elements: [
      { id: "top-bar", type: "rect", x: 0, y: 0, width: 100, height: 2.5, bgColor: "#2e7d32", editable: false },
      { id: "logo", type: "image", x: 80, y: 3.5, width: 14, height: 7, isPhoto: true, editable: true, bgColor: "rgba(46,125,50,0.06)", borderRadius: 4 },
      { id: "company", type: "text", x: 10, y: 4, width: 68, height: 4, text: "کمپنی کا نام", fontFamily: "Noto Nastaliq Urdu", fontSize: 3, fontWeight: "bold", color: "#2e7d32", textAlign: "right", direction: "rtl", editable: true },
      { id: "tagline", type: "text", x: 10, y: 8, width: 68, height: 2.5, text: "آپ کا ٹیگ لائن یہاں", fontFamily: "Noto Naskh Arabic", fontSize: 1.5, color: "#666666", textAlign: "right", direction: "rtl", editable: true },
      { id: "divider-top", type: "rect", x: 5, y: 12, width: 90, height: 0.15, bgColor: "#2e7d32", editable: false },
      { id: "body", type: "text", x: 8, y: 16, width: 84, height: 65, text: "محترم جناب،\n\nیہاں خط کا مواد لکھیں...\n\n\n\n\n\nمخلص،\nآپ کا نام\nعہدہ", fontFamily: "Noto Naskh Arabic", fontSize: 1.8, color: "#333333", textAlign: "right", direction: "rtl", editable: true, lineHeight: 2.2 },
      { id: "divider-bottom", type: "rect", x: 5, y: 90, width: 90, height: 0.15, bgColor: "#2e7d32", editable: false },
      { id: "footer", type: "text", x: 5, y: 92, width: 90, height: 3, text: "پتہ: آفس نمبر 12، بلیو ایریا، اسلام آباد | فون: 0300-1234567", fontFamily: "Noto Naskh Arabic", fontSize: 1.2, color: "#888888", textAlign: "center", direction: "rtl", editable: true },
      { id: "footer-web", type: "text", x: 5, y: 95.5, width: 90, height: 2.5, text: "www.company.com", fontFamily: "Inter", fontSize: 1.2, color: "#2e7d32", textAlign: "center", editable: true },
    ],
  },
  {
    id: "bpad-modern-1",
    name: "Modern Notepad",
    category: "Business Pad",
    bgColor: "#FFFFFF",
    bgGradient: "linear-gradient(180deg, #FFFFFF 0%, #fafafa 100%)",
    elements: [
      { id: "sidebar", type: "rect", x: 0, y: 0, width: 2, height: 100, bgColor: "#e94560", editable: false },
      { id: "logo", type: "image", x: 5, y: 3, width: 10, height: 5, isPhoto: true, editable: true, bgColor: "rgba(233,69,96,0.06)", borderRadius: 4 },
      { id: "company", type: "text", x: 18, y: 3.5, width: 60, height: 3.5, text: "COMPANY NAME", fontFamily: "Inter", fontSize: 2, fontWeight: "bold", color: "#1a1a2e", textAlign: "left", editable: true },
      { id: "tagline", type: "text", x: 18, y: 6.5, width: 60, height: 2, text: "Innovation • Excellence • Growth", fontFamily: "Inter", fontSize: 1.2, color: "#e94560", textAlign: "left", editable: true },
      { id: "divider-top", type: "rect", x: 4, y: 11, width: 92, height: 0.1, bgColor: "#e0e0e0", editable: false },
      { id: "body", type: "text", x: 6, y: 14, width: 88, height: 72, text: "Write your content here...", fontFamily: "Inter", fontSize: 1.6, color: "#333333", textAlign: "left", editable: true, lineHeight: 2.5 },
      { id: "bottom-bar", type: "rect", x: 0, y: 92, width: 100, height: 8, bgColor: "#1a1a2e", editable: false },
      { id: "footer", type: "text", x: 5, y: 94, width: 90, height: 4, text: "+92 300 1234567  |  info@company.com  |  www.company.com", fontFamily: "Inter", fontSize: 1.1, color: "#FFFFFF", textAlign: "center", editable: true },
    ],
  },
];
