import { PosterTemplate } from "./types";

export const POSTER_TEMPLATES: PosterTemplate[] = [
  // ===== POLITICAL BANNERS =====
  {
    id: "political-green-1",
    name: "Political Rally - Green",
    nameUrdu: "سیاسی جلسہ",
    category: "Political",
    bgColor: "#006400",
    bgGradient: "linear-gradient(135deg, #004d00 0%, #008000 50%, #006400 100%)",
    elements: [
      { id: "flag-bar", type: "rect", x: 0, y: 0, width: 100, height: 8, bgColor: "#004d00", opacity: 0.9, editable: false },
      { id: "photo", type: "image", x: 35, y: 12, width: 30, height: 30, isPhoto: true, editable: true, bgColor: "rgba(255,255,255,0.2)", borderRadius: 50 },
      { id: "name-urdu", type: "text", x: 10, y: 46, width: 80, height: 10, text: "نام یہاں لکھیں", fontFamily: "Noto Nastaliq Urdu", fontSize: 5, fontWeight: "bold", color: "#FFFFFF", textAlign: "center", direction: "rtl", editable: true },
      { id: "title-urdu", type: "text", x: 10, y: 56, width: 80, height: 8, text: "امیدوار برائے", fontFamily: "Noto Nastaliq Urdu", fontSize: 3.5, color: "#FFD700", textAlign: "center", direction: "rtl", editable: true },
      { id: "slogan", type: "text", x: 5, y: 67, width: 90, height: 12, text: "ترقی کا سفر جاری رہے گا", fontFamily: "Noto Nastaliq Urdu", fontSize: 4, fontWeight: "bold", color: "#FFFFFF", textAlign: "center", direction: "rtl", editable: true },
      { id: "party-bar", type: "rect", x: 0, y: 82, width: 100, height: 18, bgColor: "rgba(0,0,0,0.4)", editable: false },
      { id: "party-name", type: "text", x: 10, y: 85, width: 80, height: 6, text: "پارٹی کا نام", fontFamily: "Noto Nastaliq Urdu", fontSize: 3, color: "#FFD700", textAlign: "center", direction: "rtl", editable: true },
      { id: "contact", type: "text", x: 10, y: 92, width: 80, height: 5, text: "رابطہ: 0300-0000000", fontFamily: "Noto Naskh Arabic", fontSize: 2.5, color: "#FFFFFF", textAlign: "center", direction: "rtl", editable: true },
    ],
  },
  {
    id: "political-red-1",
    name: "Political Campaign - Red",
    nameUrdu: "سیاسی مہم",
    category: "Political",
    bgColor: "#8B0000",
    bgGradient: "linear-gradient(180deg, #8B0000 0%, #CC0000 50%, #8B0000 100%)",
    elements: [
      { id: "top-accent", type: "rect", x: 0, y: 0, width: 100, height: 5, bgColor: "#FFD700", editable: false },
      { id: "photo", type: "image", x: 5, y: 10, width: 35, height: 45, isPhoto: true, editable: true, bgColor: "rgba(255,255,255,0.15)", borderRadius: 5 },
      { id: "name-urdu", type: "text", x: 42, y: 12, width: 55, height: 10, text: "امیدوار کا نام", fontFamily: "Noto Nastaliq Urdu", fontSize: 5, fontWeight: "bold", color: "#FFD700", textAlign: "right", direction: "rtl", editable: true },
      { id: "position", type: "text", x: 42, y: 24, width: 55, height: 8, text: "صدر / چیئرمین", fontFamily: "Noto Nastaliq Urdu", fontSize: 3.5, color: "#FFFFFF", textAlign: "right", direction: "rtl", editable: true },
      { id: "slogan", type: "text", x: 42, y: 35, width: 55, height: 15, text: "عوام کی خدمت ہمارا مشن", fontFamily: "Noto Nastaliq Urdu", fontSize: 3.5, fontWeight: "bold", color: "#FFFFFF", textAlign: "right", direction: "rtl", editable: true },
      { id: "divider", type: "rect", x: 10, y: 58, width: 80, height: 0.5, bgColor: "#FFD700", editable: false },
      { id: "details", type: "text", x: 5, y: 62, width: 90, height: 15, text: "جلسہ عام\n مقام: جناح پارک\nتاریخ: ___________", fontFamily: "Noto Naskh Arabic", fontSize: 3, color: "#FFFFFF", textAlign: "center", direction: "rtl", editable: true, lineHeight: 1.8 },
      { id: "bottom-bar", type: "rect", x: 0, y: 85, width: 100, height: 15, bgColor: "rgba(0,0,0,0.5)", editable: false },
      { id: "contact", type: "text", x: 10, y: 88, width: 80, height: 5, text: "ووٹ ڈالیں - نشان: ___________", fontFamily: "Noto Nastaliq Urdu", fontSize: 3, fontWeight: "bold", color: "#FFD700", textAlign: "center", direction: "rtl", editable: true },
    ],
  },

  // ===== BUSINESS BANNERS =====
  {
    id: "business-blue-1",
    name: "Business Grand Opening",
    nameUrdu: "کاروباری افتتاح",
    category: "Business",
    bgColor: "#1a237e",
    bgGradient: "linear-gradient(135deg, #0d1b4a 0%, #1a237e 50%, #283593 100%)",
    elements: [
      { id: "accent-top", type: "rect", x: 0, y: 0, width: 100, height: 3, bgColor: "#FFD700", editable: false },
      { id: "heading", type: "text", x: 5, y: 8, width: 90, height: 12, text: "گرینڈ اوپننگ", fontFamily: "Noto Nastaliq Urdu", fontSize: 6, fontWeight: "bold", color: "#FFD700", textAlign: "center", direction: "rtl", editable: true },
      { id: "shop-name", type: "text", x: 10, y: 22, width: 80, height: 10, text: "دکان کا نام یہاں لکھیں", fontFamily: "Noto Nastaliq Urdu", fontSize: 4.5, fontWeight: "bold", color: "#FFFFFF", textAlign: "center", direction: "rtl", editable: true },
      { id: "photo", type: "image", x: 25, y: 35, width: 50, height: 25, isPhoto: true, editable: true, bgColor: "rgba(255,255,255,0.1)", borderRadius: 8 },
      { id: "desc", type: "text", x: 10, y: 63, width: 80, height: 10, text: "خصوصی رعایت - ابتدائی گاہکوں کے لیے", fontFamily: "Noto Naskh Arabic", fontSize: 3, color: "#E0E0E0", textAlign: "center", direction: "rtl", editable: true },
      { id: "discount", type: "text", x: 20, y: 74, width: 60, height: 10, text: "50% OFF", fontFamily: "Inter", fontSize: 7, fontWeight: "bold", color: "#FF4444", textAlign: "center", direction: "ltr", editable: true },
      { id: "bottom", type: "rect", x: 0, y: 88, width: 100, height: 12, bgColor: "rgba(0,0,0,0.4)", editable: false },
      { id: "address", type: "text", x: 5, y: 90, width: 90, height: 8, text: "پتہ: ___________ | فون: 0300-0000000", fontFamily: "Noto Naskh Arabic", fontSize: 2.5, color: "#FFFFFF", textAlign: "center", direction: "rtl", editable: true },
    ],
  },
  {
    id: "business-gold-1",
    name: "Business Sale Banner",
    nameUrdu: "سیل بینر",
    category: "Business",
    bgColor: "#1a1a2e",
    bgGradient: "linear-gradient(180deg, #16213e 0%, #1a1a2e 100%)",
    elements: [
      { id: "sale-badge", type: "circle", x: 35, y: 5, width: 30, height: 20, bgColor: "#FF0000", editable: false },
      { id: "sale-text", type: "text", x: 35, y: 8, width: 30, height: 14, text: "SALE", fontFamily: "Inter", fontSize: 5, fontWeight: "bold", color: "#FFFFFF", textAlign: "center", editable: false },
      { id: "title", type: "text", x: 5, y: 28, width: 90, height: 10, text: "بڑی سیل شروع", fontFamily: "Noto Nastaliq Urdu", fontSize: 5.5, fontWeight: "bold", color: "#FFD700", textAlign: "center", direction: "rtl", editable: true },
      { id: "subtitle", type: "text", x: 10, y: 40, width: 80, height: 8, text: "تمام اشیاء پر بھاری رعایت", fontFamily: "Noto Nastaliq Urdu", fontSize: 3.5, color: "#FFFFFF", textAlign: "center", direction: "rtl", editable: true },
      { id: "photo", type: "image", x: 20, y: 50, width: 60, height: 25, isPhoto: true, editable: true, bgColor: "rgba(255,255,255,0.08)", borderRadius: 8 },
      { id: "offer", type: "text", x: 10, y: 78, width: 80, height: 8, text: "70% تک رعایت", fontFamily: "Noto Nastaliq Urdu", fontSize: 4, fontWeight: "bold", color: "#FF4444", textAlign: "center", direction: "rtl", editable: true },
      { id: "contact", type: "text", x: 10, y: 90, width: 80, height: 6, text: "آج ہی تشریف لائیں | 0300-0000000", fontFamily: "Noto Naskh Arabic", fontSize: 2.5, color: "#AAAAAA", textAlign: "center", direction: "rtl", editable: true },
    ],
  },

  // ===== EVENT BANNERS =====
  {
    id: "event-eid-1",
    name: "Eid Mubarak Poster",
    nameUrdu: "عید مبارک پوسٹر",
    category: "Event",
    bgColor: "#1a3a1a",
    bgGradient: "linear-gradient(135deg, #0a2e0a 0%, #1a4d1a 50%, #2d5a2d 100%)",
    elements: [
      { id: "crescent", type: "text", x: 35, y: 3, width: 30, height: 15, text: "☪", fontFamily: "serif", fontSize: 10, color: "#FFD700", textAlign: "center", editable: false },
      { id: "eid-urdu", type: "text", x: 5, y: 20, width: 90, height: 15, text: "عید مبارک", fontFamily: "Noto Nastaliq Urdu", fontSize: 7, fontWeight: "bold", color: "#FFD700", textAlign: "center", direction: "rtl", editable: true },
      { id: "eid-eng", type: "text", x: 20, y: 36, width: 60, height: 6, text: "Eid Mubarak", fontFamily: "Inter", fontSize: 3, color: "#C0C0C0", textAlign: "center", editable: true },
      { id: "photo", type: "image", x: 30, y: 44, width: 40, height: 22, isPhoto: true, editable: true, bgColor: "rgba(255,215,0,0.1)", borderRadius: 50 },
      { id: "message", type: "text", x: 5, y: 69, width: 90, height: 12, text: "آپ کو اور آپ کی فیملی کو\nعید الفطر مبارک ہو", fontFamily: "Noto Nastaliq Urdu", fontSize: 3.5, color: "#FFFFFF", textAlign: "center", direction: "rtl", editable: true, lineHeight: 1.8 },
      { id: "from", type: "text", x: 10, y: 84, width: 80, height: 6, text: "از: آپ کا نام", fontFamily: "Noto Nastaliq Urdu", fontSize: 3, color: "#FFD700", textAlign: "center", direction: "rtl", editable: true },
      { id: "deco-bottom", type: "rect", x: 20, y: 93, width: 60, height: 0.5, bgColor: "#FFD700", opacity: 0.5, editable: false },
    ],
  },
  {
    id: "event-wedding-1",
    name: "Wedding Invitation",
    nameUrdu: "شادی کا کارڈ",
    category: "Event",
    bgColor: "#2c1810",
    bgGradient: "linear-gradient(135deg, #1a0f0a 0%, #3d1f10 50%, #5a2d15 100%)",
    elements: [
      { id: "border-top", type: "rect", x: 3, y: 3, width: 94, height: 0.5, bgColor: "#FFD700", editable: false },
      { id: "border-bottom", type: "rect", x: 3, y: 96, width: 94, height: 0.5, bgColor: "#FFD700", editable: false },
      { id: "heading", type: "text", x: 10, y: 6, width: 80, height: 10, text: "دعوت نامہ", fontFamily: "Noto Nastaliq Urdu", fontSize: 5, fontWeight: "bold", color: "#FFD700", textAlign: "center", direction: "rtl", editable: true },
      { id: "bismillah", type: "text", x: 15, y: 17, width: 70, height: 6, text: "بسم اللہ الرحمٰن الرحیم", fontFamily: "Noto Nastaliq Urdu", fontSize: 3, color: "#FFD700", textAlign: "center", direction: "rtl", editable: true },
      { id: "groom", type: "text", x: 10, y: 28, width: 80, height: 8, text: "دولہا: نام یہاں لکھیں", fontFamily: "Noto Nastaliq Urdu", fontSize: 4, fontWeight: "bold", color: "#FFFFFF", textAlign: "center", direction: "rtl", editable: true },
      { id: "weds", type: "text", x: 30, y: 37, width: 40, height: 6, text: "❤", fontFamily: "serif", fontSize: 4, color: "#FF6B6B", textAlign: "center", editable: false },
      { id: "bride", type: "text", x: 10, y: 44, width: 80, height: 8, text: "دلہن: نام یہاں لکھیں", fontFamily: "Noto Nastaliq Urdu", fontSize: 4, fontWeight: "bold", color: "#FFFFFF", textAlign: "center", direction: "rtl", editable: true },
      { id: "photo", type: "image", x: 25, y: 54, width: 50, height: 20, isPhoto: true, editable: true, bgColor: "rgba(255,215,0,0.08)", borderRadius: 8 },
      { id: "details", type: "text", x: 5, y: 76, width: 90, height: 12, text: "تاریخ: ___________\nمقام: ___________\nوقت: ___________", fontFamily: "Noto Naskh Arabic", fontSize: 2.8, color: "#E0D0C0", textAlign: "center", direction: "rtl", editable: true, lineHeight: 1.8 },
      { id: "footer", type: "text", x: 15, y: 91, width: 70, height: 5, text: "آپ کی تشریف آوری باعثِ عزت ہوگی", fontFamily: "Noto Nastaliq Urdu", fontSize: 2.5, color: "#FFD700", textAlign: "center", direction: "rtl", editable: true },
    ],
  },

  // ===== SOCIAL MEDIA =====
  {
    id: "social-quote-1",
    name: "Social Media Quote",
    nameUrdu: "اقتباس پوسٹ",
    category: "Social Media",
    bgColor: "#0f0f23",
    bgGradient: "linear-gradient(135deg, #0f0f23 0%, #1a1a3e 50%, #2d1b69 100%)",
    elements: [
      { id: "quote-mark", type: "text", x: 10, y: 10, width: 20, height: 15, text: "❝", fontFamily: "serif", fontSize: 10, color: "rgba(255,215,0,0.3)", textAlign: "left", editable: false },
      { id: "quote-text", type: "text", x: 10, y: 25, width: 80, height: 30, text: "یہاں اپنا اقتباس لکھیں\nمشہور شاعری یا حکمت کے الفاظ", fontFamily: "Noto Nastaliq Urdu", fontSize: 4.5, fontWeight: "bold", color: "#FFFFFF", textAlign: "center", direction: "rtl", editable: true, lineHeight: 1.8 },
      { id: "divider", type: "rect", x: 35, y: 58, width: 30, height: 0.4, bgColor: "#FFD700", editable: false },
      { id: "author", type: "text", x: 15, y: 62, width: 70, height: 8, text: "— شاعر / مصنف کا نام", fontFamily: "Noto Nastaliq Urdu", fontSize: 3, color: "#FFD700", textAlign: "center", direction: "rtl", editable: true },
      { id: "photo", type: "image", x: 35, y: 72, width: 30, height: 18, isPhoto: true, editable: true, bgColor: "rgba(255,255,255,0.05)", borderRadius: 50 },
      { id: "handle", type: "text", x: 20, y: 92, width: 60, height: 5, text: "@yourusername", fontFamily: "Inter", fontSize: 2, color: "#888888", textAlign: "center", editable: true },
    ],
  },
  {
    id: "social-promo-1",
    name: "Product Promotion",
    nameUrdu: "پروڈکٹ اشتہار",
    category: "Social Media",
    bgColor: "#1a1a1a",
    bgGradient: "linear-gradient(180deg, #1a1a1a 0%, #2d2d2d 100%)",
    elements: [
      { id: "badge", type: "rect", x: 60, y: 3, width: 35, height: 10, bgColor: "#FF0000", borderRadius: 20, editable: false },
      { id: "badge-text", type: "text", x: 60, y: 4, width: 35, height: 8, text: "NEW", fontFamily: "Inter", fontSize: 3, fontWeight: "bold", color: "#FFFFFF", textAlign: "center", editable: true },
      { id: "product-name", type: "text", x: 5, y: 8, width: 55, height: 12, text: "پروڈکٹ کا نام", fontFamily: "Noto Nastaliq Urdu", fontSize: 5, fontWeight: "bold", color: "#FFFFFF", textAlign: "right", direction: "rtl", editable: true },
      { id: "photo", type: "image", x: 10, y: 22, width: 80, height: 40, isPhoto: true, editable: true, bgColor: "rgba(255,255,255,0.05)", borderRadius: 12 },
      { id: "desc", type: "text", x: 5, y: 65, width: 90, height: 10, text: "بہترین کوالٹی | مناسب قیمت", fontFamily: "Noto Naskh Arabic", fontSize: 3, color: "#CCCCCC", textAlign: "center", direction: "rtl", editable: true },
      { id: "price", type: "text", x: 25, y: 77, width: 50, height: 10, text: "Rs. 999/-", fontFamily: "Inter", fontSize: 5, fontWeight: "bold", color: "#00FF88", textAlign: "center", editable: true },
      { id: "cta", type: "rect", x: 20, y: 89, width: 60, height: 8, bgColor: "#FFD700", borderRadius: 25, editable: false },
      { id: "cta-text", type: "text", x: 20, y: 90, width: 60, height: 6, text: "ابھی آرڈر کریں", fontFamily: "Noto Nastaliq Urdu", fontSize: 2.8, fontWeight: "bold", color: "#000000", textAlign: "center", direction: "rtl", editable: true },
    ],
  },

  // ===== RESTAURANT MENU CARDS =====
  {
    id: "menu-bbq-deals",
    name: "BBQ Deals Menu",
    nameUrdu: "بار بی کیو ڈیلز مینو",
    category: "Menu Card",
    bgColor: "#FFD600",
    bgGradient: "linear-gradient(180deg, #FFD600 0%, #FFA000 100%)",
    elements: [
      { id: "header-bar", type: "rect", x: 0, y: 0, width: 100, height: 12, bgColor: "#D32F2F", editable: false },
      { id: "shop-name", type: "text", x: 5, y: 1, width: 90, height: 10, text: "ریسٹورنٹ کا نام", fontFamily: "Noto Nastaliq Urdu", fontSize: 5, fontWeight: "bold", color: "#FFFFFF", textAlign: "center", direction: "rtl", editable: true },
      { id: "deal1-bg", type: "rect", x: 3, y: 14, width: 30, height: 24, bgColor: "#1A237E", borderRadius: 8, editable: false },
      { id: "deal1-title", type: "text", x: 3, y: 14, width: 30, height: 5, text: "ڈیل 1", fontFamily: "Noto Nastaliq Urdu", fontSize: 2.5, fontWeight: "bold", color: "#FFD700", textAlign: "center", direction: "rtl", editable: true },
      { id: "deal1-items", type: "text", x: 4, y: 19, width: 28, height: 14, text: "1 تکہ بوٹی\n1 چکن کباب\n1 لیٹر بوتل", fontFamily: "Noto Nastaliq Urdu", fontSize: 2, color: "#FFFFFF", textAlign: "right", direction: "rtl", editable: true, lineHeight: 1.6 },
      { id: "deal1-price", type: "text", x: 3, y: 33, width: 30, height: 5, text: "999/-", fontFamily: "Inter", fontSize: 3, fontWeight: "bold", color: "#FF0000", textAlign: "center", editable: true },
      { id: "deal2-bg", type: "rect", x: 35, y: 14, width: 30, height: 24, bgColor: "#1A237E", borderRadius: 8, editable: false },
      { id: "deal2-title", type: "text", x: 35, y: 14, width: 30, height: 5, text: "ڈیل 2", fontFamily: "Noto Nastaliq Urdu", fontSize: 2.5, fontWeight: "bold", color: "#FFD700", textAlign: "center", direction: "rtl", editable: true },
      { id: "deal2-items", type: "text", x: 36, y: 19, width: 28, height: 14, text: "2 تکہ بوٹی\n2 چکن کباب\n1 لیٹر بوتل", fontFamily: "Noto Nastaliq Urdu", fontSize: 2, color: "#FFFFFF", textAlign: "right", direction: "rtl", editable: true, lineHeight: 1.6 },
      { id: "deal2-price", type: "text", x: 35, y: 33, width: 30, height: 5, text: "1499/-", fontFamily: "Inter", fontSize: 3, fontWeight: "bold", color: "#FF0000", textAlign: "center", editable: true },
      { id: "deal3-bg", type: "rect", x: 67, y: 14, width: 30, height: 24, bgColor: "#1A237E", borderRadius: 8, editable: false },
      { id: "deal3-title", type: "text", x: 67, y: 14, width: 30, height: 5, text: "ڈیل 3", fontFamily: "Noto Nastaliq Urdu", fontSize: 2.5, fontWeight: "bold", color: "#FFD700", textAlign: "center", direction: "rtl", editable: true },
      { id: "deal3-items", type: "text", x: 68, y: 19, width: 28, height: 14, text: "3 تکہ بوٹی\n2 ملائی بوٹی\n1.5 لیٹر بوتل", fontFamily: "Noto Nastaliq Urdu", fontSize: 2, color: "#FFFFFF", textAlign: "right", direction: "rtl", editable: true, lineHeight: 1.6 },
      { id: "deal3-price", type: "text", x: 67, y: 33, width: 30, height: 5, text: "1999/-", fontFamily: "Inter", fontSize: 3, fontWeight: "bold", color: "#FF0000", textAlign: "center", editable: true },
      { id: "deal4-bg", type: "rect", x: 3, y: 40, width: 30, height: 24, bgColor: "#1A237E", borderRadius: 8, editable: false },
      { id: "deal4-title", type: "text", x: 3, y: 40, width: 30, height: 5, text: "فیملی ڈیل", fontFamily: "Noto Nastaliq Urdu", fontSize: 2.5, fontWeight: "bold", color: "#FFD700", textAlign: "center", direction: "rtl", editable: true },
      { id: "deal4-items", type: "text", x: 4, y: 45, width: 28, height: 14, text: "4 تکہ بوٹی\n2 کباب\n1 ملائی بوٹی\n1.5 لیٹر بوتل", fontFamily: "Noto Nastaliq Urdu", fontSize: 2, color: "#FFFFFF", textAlign: "right", direction: "rtl", editable: true, lineHeight: 1.6 },
      { id: "deal4-price", type: "text", x: 3, y: 59, width: 30, height: 5, text: "2499/-", fontFamily: "Inter", fontSize: 3, fontWeight: "bold", color: "#FF0000", textAlign: "center", editable: true },
      { id: "deal5-bg", type: "rect", x: 35, y: 40, width: 30, height: 24, bgColor: "#1A237E", borderRadius: 8, editable: false },
      { id: "deal5-title", type: "text", x: 35, y: 40, width: 30, height: 5, text: "سپیشل ڈیل", fontFamily: "Noto Nastaliq Urdu", fontSize: 2.5, fontWeight: "bold", color: "#FFD700", textAlign: "center", direction: "rtl", editable: true },
      { id: "deal5-items", type: "text", x: 36, y: 45, width: 28, height: 14, text: "1 پاؤ چکن\n2 تکہ بوٹی\n2 کباب\n1 لیٹر بوتل", fontFamily: "Noto Nastaliq Urdu", fontSize: 2, color: "#FFFFFF", textAlign: "right", direction: "rtl", editable: true, lineHeight: 1.6 },
      { id: "deal5-price", type: "text", x: 35, y: 59, width: 30, height: 5, text: "2799/-", fontFamily: "Inter", fontSize: 3, fontWeight: "bold", color: "#FF0000", textAlign: "center", editable: true },
      { id: "deal6-bg", type: "rect", x: 67, y: 40, width: 30, height: 24, bgColor: "#1A237E", borderRadius: 8, editable: false },
      { id: "deal6-title", type: "text", x: 67, y: 40, width: 30, height: 5, text: "پارٹی ڈیل", fontFamily: "Noto Nastaliq Urdu", fontSize: 2.5, fontWeight: "bold", color: "#FFD700", textAlign: "center", direction: "rtl", editable: true },
      { id: "deal6-items", type: "text", x: 68, y: 45, width: 28, height: 14, text: "6 تکہ بوٹی\n4 کباب\n2 ملائی بوٹی\n2 لیٹر بوتل", fontFamily: "Noto Nastaliq Urdu", fontSize: 2, color: "#FFFFFF", textAlign: "right", direction: "rtl", editable: true, lineHeight: 1.6 },
      { id: "deal6-price", type: "text", x: 67, y: 59, width: 30, height: 5, text: "3999/-", fontFamily: "Inter", fontSize: 3, fontWeight: "bold", color: "#FF0000", textAlign: "center", editable: true },
      { id: "photo1", type: "image", x: 10, y: 66, width: 25, height: 14, isPhoto: true, editable: true, bgColor: "rgba(255,255,255,0.2)", borderRadius: 8 },
      { id: "photo2", type: "image", x: 38, y: 66, width: 25, height: 14, isPhoto: true, editable: true, bgColor: "rgba(255,255,255,0.2)", borderRadius: 8 },
      { id: "photo3", type: "image", x: 66, y: 66, width: 25, height: 14, isPhoto: true, editable: true, bgColor: "rgba(255,255,255,0.2)", borderRadius: 8 },
      { id: "footer-bar", type: "rect", x: 0, y: 82, width: 100, height: 18, bgColor: "#D32F2F", editable: false },
      { id: "delivery", type: "text", x: 5, y: 83, width: 90, height: 6, text: "فری ہوم ڈیلیوری", fontFamily: "Noto Nastaliq Urdu", fontSize: 4, fontWeight: "bold", color: "#FFFFFF", textAlign: "center", direction: "rtl", editable: true },
      { id: "phone", type: "text", x: 5, y: 90, width: 90, height: 8, text: "0300-0000000 | 0336-0000000", fontFamily: "Inter", fontSize: 3, fontWeight: "bold", color: "#FFD700", textAlign: "center", editable: true },
    ],
  },
  {
    id: "menu-full-price",
    name: "Full Price Menu",
    nameUrdu: "مکمل مینو کارڈ",
    category: "Menu Card",
    bgColor: "#FFF8E1",
    bgGradient: "linear-gradient(180deg, #FFF8E1 0%, #FFE082 100%)",
    elements: [
      { id: "header-bar", type: "rect", x: 0, y: 0, width: 100, height: 14, bgColor: "#C62828", editable: false },
      { id: "shop-name", type: "text", x: 5, y: 1, width: 90, height: 12, text: "ریسٹورنٹ کا نام یہاں لکھیں", fontFamily: "Noto Nastaliq Urdu", fontSize: 5, fontWeight: "bold", color: "#FFFFFF", textAlign: "center", direction: "rtl", editable: true },
      { id: "col1-bg", type: "rect", x: 2, y: 16, width: 30, height: 60, bgColor: "#1A237E", borderRadius: 8, editable: false },
      { id: "col1-title", type: "text", x: 2, y: 16, width: 30, height: 5, text: "پراٹھا", fontFamily: "Noto Nastaliq Urdu", fontSize: 3, fontWeight: "bold", color: "#FFD700", textAlign: "center", direction: "rtl", editable: true },
      { id: "col1-items", type: "text", x: 3, y: 22, width: 28, height: 52, text: "آلو پراٹھا — 110\nانڈہ پراٹھا — 130\nچکن پراٹھا — 220\nبیف قیمہ — 300\nآلو چکن — 200\nچیز پراٹھا — 250", fontFamily: "Noto Nastaliq Urdu", fontSize: 1.8, color: "#FFFFFF", textAlign: "right", direction: "rtl", editable: true, lineHeight: 2.2 },
      { id: "col2-bg", type: "rect", x: 34, y: 16, width: 32, height: 60, bgColor: "#00838F", borderRadius: 8, editable: false },
      { id: "col2-title", type: "text", x: 34, y: 16, width: 32, height: 5, text: "چائے / مشروبات", fontFamily: "Noto Nastaliq Urdu", fontSize: 3, fontWeight: "bold", color: "#FFD700", textAlign: "center", direction: "rtl", editable: true },
      { id: "col2-items", type: "text", x: 35, y: 22, width: 30, height: 52, text: "سادہ چائے — 70\nگڑوالی چائے — 80\nپستہ بادام — 120\nکولڈ ڈرنک — 70\n1 لیٹر کوک — 170\n1.5 لیٹر کوک — 230\nمنرل واٹر — 100", fontFamily: "Noto Nastaliq Urdu", fontSize: 1.8, color: "#FFFFFF", textAlign: "right", direction: "rtl", editable: true, lineHeight: 2.2 },
      { id: "col3-bg", type: "rect", x: 68, y: 16, width: 30, height: 60, bgColor: "#1A237E", borderRadius: 8, editable: false },
      { id: "col3-title", type: "text", x: 68, y: 16, width: 30, height: 5, text: "کھانے", fontFamily: "Noto Nastaliq Urdu", fontSize: 3, fontWeight: "bold", color: "#FFD700", textAlign: "center", direction: "rtl", editable: true },
      { id: "col3-items", type: "text", x: 69, y: 22, width: 28, height: 52, text: "چکن کڑاہی — 1400\nچکن بوٹی — 180\nتکہ بوٹی — 240\nملائی بوٹی — 240\nبیف کباب — 220\nچکن کباب — 170\nلیگ پیس — 300", fontFamily: "Noto Nastaliq Urdu", fontSize: 1.8, color: "#FFFFFF", textAlign: "right", direction: "rtl", editable: true, lineHeight: 2.2 },
      { id: "footer-bar", type: "rect", x: 0, y: 80, width: 100, height: 20, bgColor: "#C62828", editable: false },
      { id: "delivery-text", type: "text", x: 5, y: 81, width: 90, height: 7, text: "فری ہوم ڈیلیوری", fontFamily: "Noto Nastaliq Urdu", fontSize: 4, fontWeight: "bold", color: "#FFD700", textAlign: "center", direction: "rtl", editable: true },
      { id: "phone-nums", type: "text", x: 5, y: 89, width: 90, height: 6, text: "0336-0000000 | 0305-0000000 | 0300-0000000", fontFamily: "Inter", fontSize: 2.5, fontWeight: "bold", color: "#FFFFFF", textAlign: "center", editable: true },
    ],
  },
  {
    id: "menu-simple-card",
    name: "Simple Menu Card",
    nameUrdu: "سادہ مینو کارڈ",
    category: "Menu Card",
    bgColor: "#212121",
    bgGradient: "linear-gradient(180deg, #212121 0%, #333333 100%)",
    elements: [
      { id: "top-accent", type: "rect", x: 0, y: 0, width: 100, height: 3, bgColor: "#FFD700", editable: false },
      { id: "shop-name", type: "text", x: 5, y: 5, width: 90, height: 10, text: "ریسٹورنٹ کا نام", fontFamily: "Noto Nastaliq Urdu", fontSize: 5, fontWeight: "bold", color: "#FFD700", textAlign: "center", direction: "rtl", editable: true },
      { id: "tagline", type: "text", x: 15, y: 15, width: 70, height: 5, text: "ذائقہ جو یاد رہے", fontFamily: "Noto Nastaliq Urdu", fontSize: 2.5, color: "#FFFFFF", textAlign: "center", direction: "rtl", editable: true },
      { id: "divider1", type: "rect", x: 30, y: 21, width: 40, height: 0.3, bgColor: "#FFD700", opacity: 0.5, editable: false },
      { id: "menu-items", type: "text", x: 5, y: 24, width: 90, height: 55, text: "چکن کڑاہی ............ 1400\nچکن بوٹی ............ 180\nتکہ بوٹی ............ 240\nملائی بوٹی ............ 240\nبیف کباب ............ 220\nچکن کباب ............ 170\nلیگ پیس ............ 300\nچیسٹ پیس ............ 380\nرائس فُل ............ 800\nچائے ............ 70\nپراٹھا ............ 110", fontFamily: "Noto Nastaliq Urdu", fontSize: 2.2, color: "#FFFFFF", textAlign: "right", direction: "rtl", editable: true, lineHeight: 2.0 },
      { id: "divider2", type: "rect", x: 30, y: 80, width: 40, height: 0.3, bgColor: "#FFD700", opacity: 0.5, editable: false },
      { id: "photo", type: "image", x: 35, y: 82, width: 30, height: 8, isPhoto: true, editable: true, bgColor: "rgba(255,215,0,0.1)", borderRadius: 8 },
      { id: "contact", type: "text", x: 10, y: 92, width: 80, height: 6, text: "آرڈر کریں: 0300-0000000", fontFamily: "Noto Nastaliq Urdu", fontSize: 2.5, fontWeight: "bold", color: "#FFD700", textAlign: "center", direction: "rtl", editable: true },
    ],
  },
  {
    id: "menu-cafe-modern",
    name: "Modern Cafe Menu",
    nameUrdu: "کیفے مینو",
    category: "Menu Card",
    bgColor: "#1B5E20",
    bgGradient: "linear-gradient(135deg, #1B5E20 0%, #2E7D32 50%, #388E3C 100%)",
    elements: [
      { id: "logo-area", type: "image", x: 35, y: 2, width: 30, height: 12, isPhoto: true, editable: true, bgColor: "rgba(255,255,255,0.15)", borderRadius: 50 },
      { id: "cafe-name", type: "text", x: 5, y: 15, width: 90, height: 8, text: "Cafe Name", fontFamily: "Inter", fontSize: 5, fontWeight: "bold", color: "#FFFFFF", textAlign: "center", editable: true },
      { id: "cafe-urdu", type: "text", x: 15, y: 23, width: 70, height: 5, text: "کیفے کا نام", fontFamily: "Noto Nastaliq Urdu", fontSize: 3, color: "#A5D6A7", textAlign: "center", direction: "rtl", editable: true },
      { id: "sec1-title", type: "text", x: 5, y: 30, width: 45, height: 5, text: "☕ گرم مشروبات", fontFamily: "Noto Nastaliq Urdu", fontSize: 2.5, fontWeight: "bold", color: "#FFD700", textAlign: "right", direction: "rtl", editable: true },
      { id: "sec1-items", type: "text", x: 5, y: 35, width: 45, height: 28, text: "کپوچینو — 350\nلاٹے — 400\nموکا — 450\nامریکانو — 300\nگرین ٹی — 200\nکڑک چائے — 100", fontFamily: "Noto Nastaliq Urdu", fontSize: 1.8, color: "#FFFFFF", textAlign: "right", direction: "rtl", editable: true, lineHeight: 2.2 },
      { id: "sec2-title", type: "text", x: 50, y: 30, width: 45, height: 5, text: "🍔 فوڈ آئٹمز", fontFamily: "Noto Nastaliq Urdu", fontSize: 2.5, fontWeight: "bold", color: "#FFD700", textAlign: "right", direction: "rtl", editable: true },
      { id: "sec2-items", type: "text", x: 50, y: 35, width: 45, height: 28, text: "زنگر برگر — 550\nچکن سینڈوچ — 400\nکلب سینڈوچ — 500\nفرائز — 250\nپاستا — 600\nپیزا — 800", fontFamily: "Noto Nastaliq Urdu", fontSize: 1.8, color: "#FFFFFF", textAlign: "right", direction: "rtl", editable: true, lineHeight: 2.2 },
      { id: "sec3-title", type: "text", x: 5, y: 65, width: 90, height: 5, text: "🧁 ڈیزرٹ", fontFamily: "Noto Nastaliq Urdu", fontSize: 2.5, fontWeight: "bold", color: "#FFD700", textAlign: "center", direction: "rtl", editable: true },
      { id: "sec3-items", type: "text", x: 15, y: 70, width: 70, height: 12, text: "چاکلیٹ کیک — 400 | چیز کیک — 450 | براؤنی — 350", fontFamily: "Noto Nastaliq Urdu", fontSize: 1.8, color: "#FFFFFF", textAlign: "center", direction: "rtl", editable: true, lineHeight: 2.0 },
      { id: "footer-bar", type: "rect", x: 0, y: 84, width: 100, height: 16, bgColor: "rgba(0,0,0,0.4)", editable: false },
      { id: "wifi", type: "text", x: 10, y: 85, width: 80, height: 4, text: "📶 Free WiFi Available", fontFamily: "Inter", fontSize: 2, color: "#A5D6A7", textAlign: "center", editable: true },
      { id: "address", type: "text", x: 5, y: 90, width: 90, height: 8, text: "پتہ یہاں لکھیں | 0300-0000000", fontFamily: "Noto Nastaliq Urdu", fontSize: 2, color: "#FFFFFF", textAlign: "center", direction: "rtl", editable: true },
    ],
  },
];
