project_id = "qxevmduydqbxdwdxyteq"

[functions.generate-script]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.generate-voice]
verify_jwt = false

[functions.generate-voice-elevenlabs]
verify_jwt = false

[functions.generate-lipsync]
verify_jwt = false

[functions.generate-music]
verify_jwt = false

[functions.generate-prompts]
verify_jwt = false